### Loading data into pandas

In [2]:
import pandas as pd
df = pd.read_csv('pokemon_data.csv')
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [3]:
df. tail()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [4]:
df_xlsx=pd.read_excel('pokemon.xlsx')
print(df_xlsx.head())
# for txt files too use pd.read_csv()

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

### Reading data in pandas

In [5]:
# To read headers or field name
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [6]:
#To read each / specific columns
# print(df['Name'].head(5)) OR
print(df['Name'][0:5])  #To access single column

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [7]:
print(df[['Name','Type 1','Type 2']][0:5])  #To access multiple columns 

# read each row
print(df.iloc[1])

                    Name Type 1  Type 2
0              Bulbasaur  Grass  Poison
1                Ivysaur  Grass  Poison
2               Venusaur  Grass  Poison
3  VenusaurMega Venusaur  Grass  Poison
4             Charmander   Fire     NaN
#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [8]:
# To read  multiple rows
# print(df.iloc[0:4])

In [9]:
# to read a specific location(R,C)
print(df.iloc[2,1])

Venusaur

In [10]:
for index,row in df.iloc[0:4].iterrows():
    print(index,row['Name'])   #To print name on each index 0 to 3

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur

In [11]:
df.loc[1] #Prints index 1

df.loc[1:3] #Prints index 1 and 2 including 3 too 
# In case of iloc it excludes 3

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [12]:
df.loc[df['Type 1']=='Fire'].head() #prints 5 rows whose type 1 is fire

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False

### Sorting or describing data

In [13]:
df.describe() #It will print the statistics related to data such count,mean,std,min,

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [14]:
print(df['HP'].mean()) # calculate mean of hp individually

69.25875

In [15]:
df.sort_values('Name',ascending=False).head() #Sorts in descending order.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False

In [16]:
df.sort_values(['Name','Type 1'],ascending=[1,0]) #sorts name in ascending and Type 1 in descending order.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

### Making changes to the data

In [17]:
# Add the total column on the given table
df['Total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [18]:
df.sort_index(ascending=False) 

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [19]:
df['Total']=df.iloc[:,4:10].sum(axis=1)
cols=list(df.columns.values)
df=df[cols[0:4]+[cols[-1]]+cols[4:12]] #swaps the column or rearranging columns
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Saving our data (Exporting into desired format)

In [20]:
# df.to_csv('modified.csv',index=False) 
# Changing the file to csv

# df.to_excel('modified.xlsx',index=False) 
# changing to excel

df.to_csv('modified.txt',index=False,sep='\t')

### Filtering Data

In [21]:
new_df=df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')].head(10)

df.loc[(df['Type 1']=='Grass') | (df['Type 2']=='Poison')].head()

print(new_df)

     #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0    1              Bulbasaur  Grass  Poison    318  45      49       49
1    2                Ivysaur  Grass  Poison    405  60      62       63
2    3               Venusaur  Grass  Poison    525  80      82       83
3    3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123
48  43                 Oddish  Grass  Poison    320  45      50       55
49  44                  Gloom  Grass  Poison    395  60      65       70
50  45              Vileplume  Grass  Poison    490  75      80       85
75  69             Bellsprout  Grass  Poison    300  50      75       35
76  70             Weepinbell  Grass  Poison    390  65      90       50
77  71             Victreebel  Grass  Poison    490  80     105       65

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
0        65       65     45           1      False
1        80       80     60           1      False
2       100      100     80           1      False
3       122      120     80           1      False
48       75       65     30           1      False
49       85       75     40           1      False
50      110       90     50           1      False
75       70       30     40           1      False
76       85       45     55           1      False
77      100       70     70           1      False

In [22]:
new_df=new_df.reset_index(drop=True,inplace=True)  

print(new_df)

None

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [24]:
# df.loc[df['Name'].str.contains('Mega')]
#Displays the rows data whose name contains substring mega

df.loc[~df['Name'].str.contains('Mega')] #displays the one which doesnt include mega string

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [25]:
import re
""" RE is Fire|Grass , since regex=True it will look for the text that can be either grass or fire
 but if regex=False it will look for exact (Fire|Grass) ie fire with or symbol followed by grass."""
# Here flags=re.I means it will ignore upper & lower case of string while searching.

' RE is Fire|Grass , since regex=True it will look for the text that can be either grass or fire\n but if regex=False it will look for exact (Fire|Grass) ie fire with or symbol followed by grass.'

In [26]:
# df.loc[df['Type 1'].str.contains('Fire|Grass',flags=re.I,regex=True)]
df.loc[df['Type 1'].str.contains('Fire|Grass',flags=re.I,regex=False)]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [27]:
df.loc[df['Name'].str.startswith('B')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
167,153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
290,267,Beautifly,Bug,Flying,395,60,70,50,100,50,65,3,False
310,286,Breloom,Grass,Fighting,460,60,130,80,60,60,70,3,False
371,339,Barboach,Water,Ground,288,50,48,43,46,41,60,3,False
375,343,Baltoy,Ground,Psychic,300,40,40,55,40,70,55,3,False
386,354,Banette,Ghost,NaN,455,64,115,65,83,63,65,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
406,371,Bagon,Dragon,NaN,300,45,75,60,40,30,50,3,False
410,374,Beldum,Steel,Psychic,300,40,55,80,35,60,30,3,False
444,399,Bidoof,Normal,NaN,250,59,45,40,35,40,31,4,False
445,400,Bibarel,Normal,Water,410,79,85,60,55,60,71,4,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
456,411,Bastiodon,Rock,Steel,495,60,52,168,47,138,30,4,False
457,412,Burmy,Bug,NaN,224,40,29,45,29,45,36,4,False
465,418,Buizel,Water,NaN,330,55,65,35,60,30,85,4,False
474,427,Buneary,Normal,NaN,350,55,66,44,44,56,85,4,False
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False
485,437,Bronzong,Steel,Psychic,500,67,89,116,79,116,33,4,False
486,438,Bonsly,Rock,NaN,290,50,80,95,10,45,10,4,False
581,522,Blitzle,Electric,NaN,295,45,60,32,50,32,76,5,False
584,525,Boldore,Rock,NaN,390,70,105,105,50,40,20,5,False
610,550,Basculin,Water,NaN,460,70,92,65,80,55,98,5,False
667,606,Beheeyem,Psychic,NaN,485,75,75,75,125,95,40,5,False
675,614,Beartic,Ice,NaN,485,95,110,80,70,80,50,5,False
686,625,Bisharp,Dark,Steel,490,65,125,100,60,70,70,5,False
687,626,Bouffalant,Normal,NaN,490,95,110,95,40,95,55,5,False
689,628,Braviary,Normal,Flying,510,100,123,75,57,75,80,5,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
727,659,Bunnelby,Normal,NaN,237,38,36,38,32,36,57,6,False
758,688,Binacle,Rock,Water,306,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,500,72,105,115,54,86,68,6,False
788,712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False

In [28]:
df.loc[df['Name'].str.contains('^pi[a-z]*',flags=re.I,regex=True)] #print names that starts with pi

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False

### Conditional changes

In [29]:
df.loc[df['Type 1']=='Fire','Type 1']='Flamer'
df

df.loc[df['Total']>500,['Generation','Legendary']]= ['TEST1','TEST2'] 
#This will change the value of Generation to TEST1 and legendary to TEST2 if the Total value is greater than 500

df

C:\Users\Dell\AppData\Local\Temp\ipykernel_15744\2904001607.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'TEST1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Total']>500,['Generation','Legendary']]= ['TEST1','TEST2']
C:\Users\Dell\AppData\Local\Temp\ipykernel_15744\2904001607.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'TEST2' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[df['Total']>500,['Generation','Legendary']]= ['TEST1','TEST2']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,TEST1,TEST2
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,TEST1,TEST2
4,4,Charmander,Flamer,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,TEST1,TEST2
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,TEST1,TEST2
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,TEST1,TEST2
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,TEST1,TEST2
799,721,Volcanion,Flamer,Water,600,80,110,120,130,90,70,TEST1,TEST2

### Aggrerate Statistics(Groupby)

In [30]:
df = pd.read_csv('modified.csv')
# df.groupby(['Type 1']).mean(numeric_only=True).sort_values('Defense',ascending=False)

df.groupby('Type 1').sum(numeric_only=True).head()

df.groupby('Type 1').count() 
df.groupby(['Type 1','Type 2']).count()

                  #  Name  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
Type 1 Type 2
Bug    Electric   2     2      2   2       2        2        2        2
       Fighting   2     2      2   2       2        2        2        2
       Fire       2     2      2   2       2        2        2        2
       Flying    14    14     14  14      14       14       14       14
       Ghost      1     1      1   1       1        1        1        1
...              ..   ...    ...  ..     ...      ...      ...      ...
Water  Ice        3     3      3   3       3        3        3        3
       Poison     3     3      3   3       3        3        3        3
       Psychic    5     5      5   5       5        5        5        5
       Rock       4     4      4   4       4        4        4        4
       Steel      1     1      1   1       1        1        1        1

                 Speed  Generation  Legendary
Type 1 Type 2
Bug    Electric      2           2          2
       Fighting      2           2          2
       Fire          2           2          2
       Flying       14          14         14
       Ghost         1           1          1
...                ...         ...        ...
Water  Ice           3           3          3
       Poison        3           3          3
       Psychic       5           5          5
       Rock          4           4          4
       Steel         1           1          1

[136 rows x 11 columns]

### Working with large amounts of data

In [31]:
for df in pd.read_csv('modified.csv',chunksize=5):
    print("CHUNK DF")
    print(df)

CHUNK DF
   #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0  1              Bulbasaur  Grass  Poison    318  45      49       49
1  2                Ivysaur  Grass  Poison    405  60      62       63
2  3               Venusaur  Grass  Poison    525  80      82       83
3  3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123
4  4             Charmander   Fire     NaN    309  39      52       43

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
0       65       65     45           1      False
1       80       80     60           1      False
2      100      100     80           1      False
3      122      120     80           1      False
4       60       50     65           1      False
CHUNK DF
   #                       Name Type 1  Type 2  Total  HP  Attack  Defense  \
5  5                 Charmeleon   Fire     NaN    405  58      64       58
6  6                  Charizard   Fire  Flying    534  78      84       78
7  6  CharizardMega Charizard X   Fire  Dragon    634  78     130      111
8  6  CharizardMega Charizard Y   Fire  Flying    634  78     104       78
9  7                   Squirtle  Water     NaN    314  44      48       65

   Sp. Atk  Sp. Def  Speed  Generation  Legendary
5       80       65     80           1      False
6      109       85    100           1      False
7      130       85    100           1      False
8      159      115    100           1      False
9       50       64     43           1      False
CHUNK DF
     #                     Name Type 1  Type 2  Total  HP  Attack  Defense  \
10   8                Wartortle  Water     NaN    405  59      63       80
11   9                Blastoise  Water     NaN    530  79      83      100
12   9  BlastoiseMega Blastoise  Water     NaN    630  79     103      120
13  10                 Caterpie    Bug     NaN    195  45      30       35
14  11                  Metapod    Bug     NaN    205  50      20       55

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
10       65       80     58           1      False
11       85      105     78           1      False
12      135      115     78           1      False
13       20       20     45           1      False
14       25       25     30           1      False
CHUNK DF
     #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
15  12             Butterfree    Bug  Flying    395  60      45       50
16  13                 Weedle    Bug  Poison    195  40      35       30
17  14                 Kakuna    Bug  Poison    205  45      25       50
18  15               Beedrill    Bug  Poison    395  65      90       40
19  15  BeedrillMega Beedrill    Bug  Poison    495  65     150       40

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
15       90       80     70           1      False
16       20       20     50           1      False
17       25       25     35           1      False
18       45       80     75           1      False
19       15       80    145           1      False
CHUNK DF
     #                 Name  Type 1  Type 2  Total  HP  Attack  Defense  \
20  16               Pidgey  Normal  Flying    251  40      45       40
21  17            Pidgeotto  Normal  Flying    349  63      60       55
22  18              Pidgeot  Normal  Flying    479  83      80       75
23  18  PidgeotMega Pidgeot  Normal  Flying    579  83      80       80
24  19              Rattata  Normal     NaN    253  30      56       35

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
20       35       35     56           1      False
21       50       50     71           1      False
22       70       70    101           1      False
23      135       80    121           1      False
24       25       35     72           1      False
CHUNK DF
     #      Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
25  20  Raticate  Normal     NaN    413  55      81       60       50
26  21   Spearow  Normal  Flying    262  40      60       30       31
27  22    Fearow  Normal  Flying    442  65      90       65       61
28  23     Ekans  Poison     NaN    288  35      60       44       40
29  24     Arbok  Poison     NaN    438  60      85       69       65

    Sp. Def  Speed  Generation  Legendary
25       70     97           1      False
26       31     70           1      False
27       61    100           1      False
28       54     55           1      False
29       79     80           1      False
CHUNK DF
     #              Name    Type 1  Type 2  Total  HP  Attack  Defense  \
30  25           Pikachu  Electric     NaN    320  35      55       40
31  26            Raichu  Electric     NaN    485  60      90       55
32  27         Sandshrew    Ground     NaN    300  50      75       85
33  28         Sandslash    Ground     NaN    450  75     100      110
34  29  Nidoran (Female)    Poison     NaN    275  55      47       52

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
30       50       50     90           1      False
31       90       80    110           1      False
32       20       30     40           1      False
33       45       55     65           1      False
34       40       40     41           1      False
CHUNK DF
     #            Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
35  30        Nidorina  Poison     NaN    365  70      62       67       55
36  31       Nidoqueen  Poison  Ground    505  90      92       87       75
37  32  Nidoran (Male)  Poison     NaN    273  46      57       40       40
38  33        Nidorino  Poison     NaN    365  61      72       57       55
39  34        Nidoking  Poison  Ground    505  81     102       77       85

    Sp. Def  Speed  Generation  Legendary
35       55     56           1      False
36       85     76           1      False
37       40     50           1      False
38       55     65           1      False
39       75     85           1      False
CHUNK DF
     #        Name  Type 1 Type 2  Total   HP  Attack  Defense  Sp. Atk  \
40  35    Clefairy   Fairy    NaN    323   70      45       48       60
41  36    Clefable   Fairy    NaN    483   95      70       73       95
42  37      Vulpix    Fire    NaN    299   38      41       40       50
43  38   Ninetales    Fire    NaN    505   73      76       75       81
44  39  Jigglypuff  Normal  Fairy    270  115      45       20       45

    Sp. Def  Speed  Generation  Legendary
40       65     35           1      False
41       90     60           1      False
42       65     65           1      False
43      100    100           1      False
44       25     20           1      False
CHUNK DF
     #        Name  Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
45  40  Wigglytuff  Normal   Fairy    435  140      70       45       85
46  41       Zubat  Poison  Flying    245   40      45       35       30
47  42      Golbat  Poison  Flying    455   75      80       70       65
48  43      Oddish   Grass  Poison    320   45      50       55       75
49  44       Gloom   Grass  Poison    395   60      65       70       85

    Sp. Def  Speed  Generation  Legendary
45       50     45           1      False
46       40     55           1      False
47       75     90           1      False
48       65     30           1      False
49       75     40           1      False
CHUNK DF
     #       Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
50  45  Vileplume  Grass  Poison    490  75      80       85      110
51  46      Paras    Bug   Grass    285  35      70       55       45
52  47   Parasect    Bug   Grass    405  60      95       80       60
53  48    Venonat    Bug  Poison    305  60      55       50       40
54  49   Venomoth    Bug  Poison    450  70      65       60       90

    Sp. Def  Speed  Generation  Legendary
50       90     50           1      False
51       55     25           1      False
52       80     30           1      False
53       55     45           1      False
54       75     90           1      False
CHUNK DF
     #     Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
55  50  Diglett  Ground     NaN    265  10      55       25       35       45
56  51  Dugtrio  Ground     NaN    405  35      80       50       50       70
57  52   Meowth  Normal     NaN    290  40      45       35       40       40
58  53  Persian  Normal     NaN    440  65      70       60       65       65
59  54  Psyduck   Water     NaN    320  50      52       48       65       50

    Speed  Generation  Legendary
55     95           1      False
56    120           1      False
57     90           1      False
58    115           1      False
59     55           1      False
CHUNK DF
     #       Name    Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
60  55    Golduck     Water     NaN    500  80      82       78       95
61  56     Mankey  Fighting     NaN    305  40      80       35       35
62  57   Primeape  Fighting     NaN    455  65     105       60       60
63  58  Growlithe      Fire     NaN    350  55      70       45       70
64  59   Arcanine      Fire     NaN    555  90     110       80      100

    Sp. Def  Speed  Generation  Legendary
60       80     85           1      False
61       45     70           1      False
62       70     95           1      False
63       50     60           1      False
64       80     95           1      False
CHUNK DF
     #       Name   Type 1    Type 2  Total  HP  Attack  Defense  Sp. Atk  \
65  60    Poliwag    Water       NaN    300  40      50       40       40
66  61  Poliwhirl    Water       NaN    385  65      65       65       50
67  62  Poliwrath    Water  Fighting    510  90      95       95       70
68  63       Abra  Psychic       NaN    310  25      20       15      105
69  64    Kadabra  Psychic       NaN    400  40      35       30      120

    Sp. Def  Speed  Generation  Legendary
65       40     90           1      False
66       50     90           1      False
67       90     70           1      False
68       55     90           1      False
69       70    105           1      False
CHUNK DF
     #                   Name    Type 1  Type 2  Total  HP  Attack  Defense  \
70  65               Alakazam   Psychic     NaN    500  55      50       45
71  65  AlakazamMega Alakazam   Psychic     NaN    590  55      50       65
72  66                 Machop  Fighting     NaN    305  70      80       50
73  67                Machoke  Fighting     NaN    405  80     100       70
74  68                Machamp  Fighting     NaN    505  90     130       80

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
70      135       95    120           1      False
71      175       95    150           1      False
72       35       35     35           1      False
73       50       60     45           1      False
74       65       85     55           1      False
CHUNK DF
     #        Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
75  69  Bellsprout  Grass  Poison    300  50      75       35       70
76  70  Weepinbell  Grass  Poison    390  65      90       50       85
77  71  Victreebel  Grass  Poison    490  80     105       65      100
78  72   Tentacool  Water  Poison    335  40      40       35       50
79  73  Tentacruel  Water  Poison    515  80      70       65       80

    Sp. Def  Speed  Generation  Legendary
75       30     40           1      False
76       45     55           1      False
77       70     70           1      False
78      100     70           1      False
79      120    100           1      False
CHUNK DF
     #      Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
80  74   Geodude   Rock  Ground    300  40      80      100       30       30
81  75  Graveler   Rock  Ground    390  55      95      115       45       45
82  76     Golem   Rock  Ground    495  80     120      130       55       65
83  77    Ponyta   Fire     NaN    410  50      85       55       65       65
84  78  Rapidash   Fire     NaN    500  65     100       70       80       80

    Speed  Generation  Legendary
80     20           1      False
81     35           1      False
82     45           1      False
83     90           1      False
84    105           1      False
CHUNK DF
     #                 Name    Type 1   Type 2  Total  HP  Attack  Defense  \
85  79             Slowpoke     Water  Psychic    315  90      65       65
86  80              Slowbro     Water  Psychic    490  95      75      110
87  80  SlowbroMega Slowbro     Water  Psychic    590  95      75      180
88  81            Magnemite  Electric    Steel    325  25      35       70
89  82             Magneton  Electric    Steel    465  50      60       95

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
85       40       40     15           1      False
86      100       80     30           1      False
87      130       80     30           1      False
88       95       55     45           1      False
89      120       70     70           1      False
CHUNK DF
     #        Name  Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
90  83  Farfetch'd  Normal  Flying    352  52      65       55       58
91  84       Doduo  Normal  Flying    310  35      85       45       35
92  85      Dodrio  Normal  Flying    460  60     110       70       60
93  86        Seel   Water     NaN    325  65      45       55       45
94  87     Dewgong   Water     Ice    475  90      70       80       70

    Sp. Def  Speed  Generation  Legendary
90       62     60           1      False
91       35     75           1      False
92       60    100           1      False
93       70     45           1      False
94       95     70           1      False
CHUNK DF
     #      Name  Type 1  Type 2  Total   HP  Attack  Defense  Sp. Atk  \
95  88    Grimer  Poison     NaN    325   80      80       50       40
96  89       Muk  Poison     NaN    500  105     105       75       65
97  90  Shellder   Water     NaN    305   30      65      100       45
98  91  Cloyster   Water     Ice    525   50      95      180       85
99  92    Gastly   Ghost  Poison    310   30      35       30      100

    Sp. Def  Speed  Generation  Legendary
95       50     25           1      False
96      100     50           1      False
97       25     40           1      False
98       45     70           1      False
99       35     80           1      False
CHUNK DF
      #               Name   Type 1  Type 2  Total  HP  Attack  Defense  \
100  93            Haunter    Ghost  Poison    405  45      50       45
101  94             Gengar    Ghost  Poison    500  60      65       60
102  94  GengarMega Gengar    Ghost  Poison    600  60      65       80
103  95               Onix     Rock  Ground    385  35      45      160
104  96            Drowzee  Psychic     NaN    328  60      48       45

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
100      115       55     95           1      False
101      130       75    110           1      False
102      170       95    130           1      False
103       30       45     70           1      False
104       43       90     42           1      False
CHUNK DF
       #       Name    Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
105   97      Hypno   Psychic     NaN    483  85      73       70       73
106   98     Krabby     Water     NaN    325  30     105       90       25
107   99    Kingler     Water     NaN    475  55     130      115       50
108  100    Voltorb  Electric     NaN    330  40      30       50       55
109  101  Electrode  Electric     NaN    480  60      50       70       80

     Sp. Def  Speed  Generation  Legendary
105      115     67           1      False
106       25     50           1      False
107       50     75           1      False
108       55    100           1      False
109       80    140           1      False
CHUNK DF
       #       Name    Type 1   Type 2  Total  HP  Attack  Defense  Sp. Atk  \
110  102  Exeggcute     Grass  Psychic    325  60      40       80       60
111  103  Exeggutor     Grass  Psychic    520  95      95       85      125
112  104     Cubone    Ground      NaN    320  50      50       95       40
113  105    Marowak    Ground      NaN    425  60      80      110       50
114  106  Hitmonlee  Fighting      NaN    455  50     120       53       35

     Sp. Def  Speed  Generation  Legendary
110       45     40           1      False
111       65     55           1      False
112       50     35           1      False
113       80     45           1      False
114      110     87           1      False
CHUNK DF
       #        Name    Type 1 Type 2  Total  HP  Attack  Defense  Sp. Atk  \
115  107  Hitmonchan  Fighting    NaN    455  50     105       79       35
116  108   Lickitung    Normal    NaN    385  90      55       75       60
117  109     Koffing    Poison    NaN    340  40      65       95       60
118  110     Weezing    Poison    NaN    490  65      90      120       85
119  111     Rhyhorn    Ground   Rock    345  80      85       95       30

     Sp. Def  Speed  Generation  Legendary
115      110     76           1      False
116       75     30           1      False
117       45     35           1      False
118       70     60           1      False
119       30     25           1      False
CHUNK DF
       #                       Name  Type 1 Type 2  Total   HP  Attack  \
120  112                     Rhydon  Ground   Rock    485  105     130
121  113                    Chansey  Normal    NaN    450  250       5
122  114                    Tangela   Grass    NaN    435   65      55
123  115                 Kangaskhan  Normal    NaN    490  105      95
124  115  KangaskhanMega Kangaskhan  Normal    NaN    590  105     125

     Defense  Sp. Atk  Sp. Def  Speed  Generation  Legendary
120      120       45       45     40           1      False
121        5       35      105     50           1      False
122      115      100       40     60           1      False
123       80       40       80     90           1      False
124      100       60      100    100           1      False
CHUNK DF
       #     Name Type 1  Type 2  Total  HP  Attack  Defense  Sp. Atk  \
125  116   Horsea  Water     NaN    295  30      40       70       70
126  117   Seadra  Water     NaN    440  55      65       95       95
127  118  Goldeen  Water     NaN    320  45      67       60       35
128  119  Seaking  Water     NaN    450  80      92       65       65
129  120   Staryu  Water     NaN    340  30      45       55       70

     Sp. Def  Speed  Generation  Legendary
125       25     60           1      False
126       45     85           1      False
127       50     63           1      False
128       80     68           1      False
129       55     85           1      False
CHUNK DF
       #        Name    Type 1   Type 2  Total  HP  Attack  Defense  Sp. Atk  \
130  121     Starmie     Water  Psychic    520  60      75       85      100
131  122    Mr. Mime   Psychic    Fairy    460  40      45       65      100
132  123     Scyther       Bug   Flying    500  70     110       80       55
133  124        Jynx       Ice  Psychic    455  65      50       35      115
134  125  Electabuzz  Electric      NaN    490  65      83       57       95

     Sp. Def  Speed  Generation  Legendary
130       85    115           1      False
131      120     90           1      False
132       80    105           1      False
133       95     95           1      False
134       85    105           1      False
CHUNK DF
       #               Name  Type 1  Type 2  Total  HP  Attack  Defense  \
135  126             Magmar    Fire     NaN    495  65      95       57
136  127             Pinsir     Bug     NaN    500  65     125      100
137  127  PinsirMega Pinsir     Bug  Flying    600  65     155      120
138  128             Tauros  Normal     NaN    490  75     100       95

### Handling Missing Data

In [32]:
df.isna()

import numpy as np
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
newd = pd.DataFrame(d)


newd

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0           NaN         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [33]:
#### Handling missing data

newd.isnull().sum() #gives the no of null elements in all columns

print(pd.isnull(newd['First Score'])) #checks if first row each indexes are null or not for first score


newd.notnull() #checks the not null condition i.e. returns true if notnull else false

0    False
1    False
2     True
3    False
Name: First Score, dtype: bool

   First Score  Second Score  Third Score
0         True          True        False
1         True         False         True
2        False          True         True
3         True         False         True

### Filling missing values

In [34]:
newd.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0           0.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [35]:
newd.fillna(method='pad') #Fills the missing value with previous value in same column

C:\Users\Dell\AppData\Local\Temp\ipykernel_15744\1979251446.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newd.fillna(method='pad') #Fills the missing value with previous value in same column

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          30.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [36]:
newd.fillna(method='bfill') #fills missing value with next value in same column

# newd['First Score'].fillna('Not Given')
newd['Second Score'].fillna('Not Given')

C:\Users\Dell\AppData\Local\Temp\ipykernel_15744\3083788128.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newd.fillna(method='bfill') #fills missing value with next value in same column

0         30.0
1    Not Given
2         56.0
3    Not Given
Name: Second Score, dtype: object

In [37]:
newd=newd.replace(to_replace=np.nan,value=-1)

newd

   First Score  Second Score  Third Score
0        100.0          30.0         -1.0
1         90.0          -1.0         40.0
2         -1.0          56.0         80.0
3         95.0          -1.0         98.0

In [38]:
df_new = pd.DataFrame({"A": [12, 4, 5, None, 1], 
                   "B": [None, 2, 54, 3, None], 
                   "C": [20, 16, None, 3, 8], 
                   "D": [14, 3, None, None, 6]})  
print(df_new)

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

In [39]:
df_new.interpolate(method='linear',limit_direction='forward')

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

### Dropping Missing values in pandas

In [40]:
df_new.dropna() #Drops the row that consist of nan values.

     A    B     C    D
1  4.0  2.0  16.0  3.0

#### Dropping rows with all null values

In [41]:
df_new.iloc[0]=[np.nan,np.nan,np.nan,np.nan]

df_new

df_new.dropna(how='all') #Removes index 0 where all columns at index 0's is NaN

     A     B     C    D
1  4.0   2.0  16.0  3.0
2  5.0  54.0   NaN  NaN
3  NaN   3.0   3.0  NaN
4  1.0   NaN   8.0  6.0

#### Dropping columns with at least one null value

In [42]:
df_new.dropna(axis=1) #since all columns contains at least one missing value all columns are dropped.

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

### Dropping rows with missing values in csv file
##### df=df.dropna(axis=0,how='any')

### GROUPING
##### It allows us to group or organize data into categories and compute value for each group

In [43]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [44]:
res=df.groupby('Type 1')['HP'].sum()
res

Type 1
Fire        80
Psychic    160
Rock       100
Name: HP, dtype: int64

In [45]:
print(df.groupby(['Name','Type 2']).groups) #groups gives the alphabetical order wise name,type2 and index

{('Diancie', 'Fairy'): [795], ('DiancieMega Diancie', 'Fairy'): [796], ('HoopaHoopa Confined', 'Ghost'): [797], ('HoopaHoopa Unbound', 'Dark'): [798], ('Volcanion', 'Water'): [799]}

In [46]:
print(df.groupby('Type 2')['Speed'].sum()) # groups by type2 and give the sum of speed of various types

Type 2
Dark      80
Fairy    160
Ghost     70
Water     70
Name: Speed, dtype: int64

In [47]:
print(df.groupby('Type 2')['Attack'].mean())

Type 2
Dark     160.0
Fairy    130.0
Ghost    110.0
Water    110.0
Name: Attack, dtype: float64

In [48]:
grp=df.groupby('Name')
grp.get_group('HoopaHoopa Confined')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True

In [49]:
for name,group in grp:
    print(name)
    print(group)

Diancie
       #     Name Type 1 Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
795  719  Diancie   Rock  Fairy    600  50     100      150      100      150

     Speed  Generation  Legendary
795     50           6       True
DiancieMega Diancie
       #                 Name Type 1 Type 2  Total  HP  Attack  Defense  \
796  719  DiancieMega Diancie   Rock  Fairy    700  50     160      110

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
796      160      110    110           6       True
HoopaHoopa Confined
       #                 Name   Type 1 Type 2  Total  HP  Attack  Defense  \
797  720  HoopaHoopa Confined  Psychic  Ghost    600  80     110       60

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
797      150      130     70           6       True
HoopaHoopa Unbound
       #                Name   Type 1 Type 2  Total  HP  Attack  Defense  \
798  720  HoopaHoopa Unbound  Psychic   Dark    680  80     160       60

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
798      170      130     80           6       True
Volcanion
       #       Name Type 1 Type 2  Total  HP  Attack  Defense  Sp. Atk  \
799  721  Volcanion   Fire  Water    600  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
799       90     70           6       True

#### AGGREGATION

In [50]:
grp1=df.groupby('Type 1')
grp1['Total'].aggregate(np.sum)

C:\Users\Dell\AppData\Local\Temp\ipykernel_15744\1388764023.py:2: FutureWarning: The provided callable <function sum at 0x0000021ECF87EF20> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1['Total'].aggregate(np.sum)

Type 1
Fire        600
Psychic    1280
Rock       1300
Name: Total, dtype: int64

In [51]:
#finding all sum,mean,std
grp2=df.groupby('Type 2')
grp2['Total'].agg([np.sum,np.mean,np.std])

C:\Users\Dell\AppData\Local\Temp\ipykernel_15744\3323402757.py:3: FutureWarning: The provided callable <function sum at 0x0000021ECF87EF20> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp2['Total'].agg([np.sum,np.mean,np.std])
C:\Users\Dell\AppData\Local\Temp\ipykernel_15744\3323402757.py:3: FutureWarning: The provided callable <function mean at 0x0000021ECF894360> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp2['Total'].agg([np.sum,np.mean,np.std])
C:\Users\Dell\AppData\Local\Temp\ipykernel_15744\3323402757.py:3: FutureWarning: The provided callable <function std at 0x0000021ECF8944A0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grp2['Total'].agg([np.sum,np.mean,np.std])

         sum   mean        std
Type 2
Dark     680  680.0        NaN
Fairy   1300  650.0  70.710678
Ghost    600  600.0        NaN
Water    600  600.0        NaN

In [52]:
#finding,mean,max,count using agg
df.groupby("Type 2").agg(
    avg_Total=("Total", "mean"),
    max_total=("Total", "max"),
    count=("Total", "count")
)

        avg_Total  max_total  count
Type 2
Dark        680.0        680      1
Fairy       650.0        700      2
Ghost       600.0        600      1
Water       600.0        600      1

In [53]:
grp3=df.groupby('Type 1')
grp3.filter(lambda x:len(x)>=2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [54]:
import pandas as pd

data1 = pd.DataFrame({'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]})

data2 = pd.DataFrame({'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]})

#### Concatenating dataframes

In [55]:
frames = [data1,data2]
res=pd.concat(frames)
res

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
0  Gaurav   22  Allahabad           MCA        NaN  1000.0
1    Anuj   32    Kannuaj           Phd        NaN  2000.0
2  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
3  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [56]:
res1 = pd.concat(frames, keys=['x', 'y'])
res1

       Name  Age    Address Qualification  Mobile No  Salary
x 0     Jai   27     Nagpur           Msc       97.0     NaN
  1  Princi   24     Kanpur            MA       91.0     NaN
  2  Gaurav   22  Allahabad           MCA       58.0     NaN
  3    Anuj   32    Kannuaj           Phd       76.0     NaN
y 0  Gaurav   22  Allahabad           MCA        NaN  1000.0
  1    Anuj   32    Kannuaj           Phd        NaN  2000.0
  2  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
  3  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [57]:
res2 = pd.concat([data1,data2],axis=1,join='inner')
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27,Nagpur,Msc,97,Gaurav,22,Allahabad,MCA,1000
1,Princi,24,Kanpur,MA,91,Anuj,32,Kannuaj,Phd,2000
2,Gaurav,22,Allahabad,MCA,58,Dhiraj,12,Allahabad,Bcom,3000
3,Anuj,32,Kannuaj,Phd,76,Hitesh,52,Kannuaj,B.hons,4000

In [58]:
res2 = pd.concat([data1,data2],axis=1,sort=True)
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27,Nagpur,Msc,97,Gaurav,22,Allahabad,MCA,1000
1,Princi,24,Kanpur,MA,91,Anuj,32,Kannuaj,Phd,2000
2,Gaurav,22,Allahabad,MCA,58,Dhiraj,12,Allahabad,Bcom,3000
3,Anuj,32,Kannuaj,Phd,76,Hitesh,52,Kannuaj,B.hons,4000

In [59]:
# concatenating by ignoring index
res2 = pd.concat([data1,data2],axis=1,ignore_index=True)
res2

        0   1          2    3   4       5   6          7       8     9
0     Jai  27     Nagpur  Msc  97  Gaurav  22  Allahabad     MCA  1000
1  Princi  24     Kanpur   MA  91    Anuj  32    Kannuaj     Phd  2000
2  Gaurav  22  Allahabad  MCA  58  Dhiraj  12  Allahabad    Bcom  3000
3    Anuj  32    Kannuaj  Phd  76  Hitesh  52    Kannuaj  B.hons  4000

#### Concatenating Dataframe and series

In [60]:
S1 = pd.Series([1000,2000,3000,4000],name='Salary')
S1

0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

In [61]:
res3 = pd.concat([data1,S1],axis=1)
res3

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc         97    1000
1  Princi   24     Kanpur            MA         91    2000
2  Gaurav   22  Allahabad           MCA         58    3000
3    Anuj   32    Kannuaj           Phd         76    4000

## Merging Dataframe

### We can merge dataframes based on common column by using "on" argument.

In [62]:

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

   key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur           B.A
2  K2  Allahabad          Bcom
3  K3    Kannuaj        B.hons

In [63]:
mer_result=pd.merge(df,df1,on='key') #It merges on the basis of key column
mer_result

  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [64]:
import pandas as pd

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

In [65]:
res4=pd.merge(df,df1,on=['key','key1']) #It merges on the basis of multiple column and gives only the data whose keys match
res4

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [66]:
# We can join using how method, left outer,right outer,full outer,inner join

In [67]:
res5 = pd.merge(df,df1,how='left',on=['key','key1'])
res5

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          Bcom
3  K3   K1    Anuj   32        NaN           NaN

### Joining Dataframes

In [68]:

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Key':['K0', 'K1', 'K2', 'K3']}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

     Name  Age Key
0     Jai   27  K0
1  Princi   24  K1
2  Gaurav   22  K2
3    Anuj   32  K3

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [69]:
res=df.join(df1)
res

     Name  Age Key Address Qualification
0     Jai   27  K0     NaN           NaN
1  Princi   24  K1     NaN           NaN
2  Gaurav   22  K2     NaN           NaN
3    Anuj   32  K3     NaN           NaN

In [70]:
res=df.join(df1,on='Key')
res

     Name  Age Key    Address Qualification
0     Jai   27  K0  Allahabad           MCA
1  Princi   24  K1        NaN           NaN
2  Gaurav   22  K2    Kannuaj           Phd
3    Anuj   32  K3  Allahabad          Bcom

In [71]:
!git add .

warning: in the working copy of '.ipynb_checkpoints/pandaspractice-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'pandaspractice.ipynb', LF will be replaced by CRLF the next time Git touches it

In [72]:
!git commit -m "Add merge and concat feature"

[main 085afeb] Add merge and concat feature
 2 files changed, 458 insertions(+), 5 deletions(-)

In [73]:
!git push origin

To https://github.com/binita21/pandas.git
   2f4135f..085afeb  main -> main

In [77]:
a = pd.DataFrame({
    'i1' : [1,2,3,4,5],
    'val' : ['a','b','c','d','e']
})
b = pd.DataFrame({
    'i1' : [1,2,9,8,5],
    'val' : ['p','q','r','s','t']
})

In [81]:
join_res=pd.merge(a,b,how='inner',on='i1')
join_res

   i1 val_x val_y
0   1     a     p
1   2     b     q
2   5     e     t

In [83]:
join_res=pd.merge(a,b,how='left',on='i1')
join_res

   i1 val_x val_y
0   1     a     p
1   2     b     q
2   3     c   NaN
3   4     d   NaN
4   5     e     t

In [84]:
join_res=pd.merge(a,b,how='right',on='i1')
join_res

   i1 val_x val_y
0   1     a     p
1   2     b     q
2   9   NaN     r
3   8   NaN     s
4   5     e     t

In [85]:
join_res=pd.merge(a,b,how='outer',on='i1')
join_res

   i1 val_x val_y
0   1     a     p
1   2     b     q
2   3     c   NaN
3   4     d   NaN
4   5     e     t
5   8   NaN     s
6   9   NaN     r

### Stacking in pandas

In [ ]:
# Stacking helps to convert columns into rows

In [88]:
a1 = pd.DataFrame({
'Math':[50,45],
'Science':[45,50]
},index=['Ram','Hari'])

In [89]:
a1

      Math  Science
Ram     50       45
Hari    45       50

In [96]:
stacked = a1.stack() #COlumn name became part of the index'
stacked

Ram   Math       50
      Science    45
Hari  Math       45
      Science    50
dtype: int64

In [95]:
stacked.unstack()

      Math  Science
Ram     50       45
Hari    45       50

In [97]:
index=pd.MultiIndex.from_tuples([
    ('Ram','Maths'),
    ('Ram','Science'),
    ('Hari','Maths'),
    ('Hari','Science')
])
df3 = pd.DataFrame({
    'Marks':[50,49,50,55]
},index=index)

In [99]:
print(df3.stack())

Ram   Maths    Marks    50
      Science  Marks    49
Hari  Maths    Marks    50
      Science  Marks    55
dtype: int64

### Data Reshaping functions (pivot table() and melt())

#### PIVOT TABLE

In [104]:
df4 = pd.DataFrame({
    'Name': ['Ram', 'Ram', 'Hari', 'Hari'],
    'Subject': ['Math', 'Science', 'Math', 'Science'],
    'Marks': [90, 85, 80, 75]
})

print(df4)

   Name  Subject  Marks
0   Ram     Math     90
1   Ram  Science     85
2  Hari     Math     80
3  Hari  Science     75

In [107]:
table = df4.pivot_table(
    index='Name',
    columns='Subject',
    values='Marks'
    
)

In [108]:
table

Subject  Math  Science
Name
Hari     80.0     75.0
Ram      90.0     85.0

In [111]:
df5 = pd.DataFrame({
    'Name': ['Ram', 'Ram'],
    'Subject': ['Math', 'Math'],
    'Marks': [90, 85,]
})

print(df5)

  Name Subject  Marks
0  Ram    Math     90
1  Ram    Math     85

In [120]:
# It returns the aggregate function by default (mean)
# Returned average marks of Ram in Maths
table1=df5.pivot_table(
    index='Name',
    columns='Subject',
    values='Marks'
)
table1

Subject  Math
Name
Ram      87.5

In [114]:
# To change aggregate function we have to explicitly change it 
table1=df5.pivot_table(
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc='sum'
)
table1

Subject  Math
Name
Ram       175

#### MELT()

In [119]:
df6 = pd.DataFrame({
    'Name': ['Ram', 'Hari'],
    'Math': [90, 80],
    'Science': [85, 75]
})

pd.melt(df6,id_vars='Name')

   Name variable  value
0   Ram     Math     90
1  Hari     Math     80
2   Ram  Science     85
3  Hari  Science     75

In [121]:
pwd

'C:\\Users\\Dell\\pythonlibraries\\pandas'

In [122]:
!git add .

warning: in the working copy of 'pandaspractice.ipynb', LF will be replaced by CRLF the next time Git touches it

In [123]:
!git commit -m "Add new functions"

[main ad04088] Add new functions
 1 file changed, 1100 insertions(+), 162 deletions(-)

In [124]:
!git push origin

To https://github.com/binita21/pandas.git
   085afeb..ad04088  main -> main

In [126]:
chunks = pd.read_csv("winedata.csv", chunksize=100)

for chunk in chunks:
    print(chunk.head())

   Unnamed: 0   country                                        description  \
0           0     Italy  Aromas include tropical fruit, broom, brimston...
1           1  Portugal  This is ripe and fruity, a wine that is smooth...
2           2        US  Tart and snappy, the flavors of lime flesh and...
3           3        US  Pineapple rind, lemon pith and orange blossom ...
4           4        US  Much like the regular bottling from 2012, this...

                          designation  points  price           province  \
0                        Vulkà Bianco      87    NaN  Sicily & Sardinia
1                            Avidagos      87   15.0              Douro
2                                 NaN      87   14.0             Oregon
3                Reserve Late Harvest      87   13.0           Michigan
4  Vintner's Reserve Wild Child Block      87   65.0             Oregon

              region_1           region_2         taster_name  \
0                 Etna                NaN       Kerin O’Keefe
1                  NaN                NaN          Roger Voss
2    Willamette Valley  Willamette Valley        Paul Gregutt
3  Lake Michigan Shore                NaN  Alexander Peartree
4    Willamette Valley  Willamette Valley        Paul Gregutt

  taster_twitter_handle                                              title  \
0          @kerinokeefe                  Nicosia 2013 Vulkà Bianco  (Etna)
1            @vossroger      Quinta dos Avidagos 2011 Avidagos Red (Douro)
2           @paulgwine       Rainstorm 2013 Pinot Gris (Willamette Valley)
3                   NaN  St. Julian 2013 Reserve Late Harvest Riesling ...
4           @paulgwine   Sweet Cheeks 2012 Vintner's Reserve Wild Child...

          variety               winery
0     White Blend              Nicosia
1  Portuguese Red  Quinta dos Avidagos
2      Pinot Gris            Rainstorm
3        Riesling           St. Julian
4      Pinot Noir         Sweet Cheeks
     Unnamed: 0 country                                        description  \
100         100      US  Fresh apple, lemon and pear flavors are accent...
101         101      US  Dusty mineral, smoke and struck flint lend a s...
102         102      US  Intensely smoky tones of struck flint and ash ...
103         103   Chile  A bright nose with green apple and citric arom...
104         104   Italy  Made with 65% Sangiovese, 20% Merlot and 15% C...

                      designation  points  price      province      region_1  \
100                           NaN      88   18.0      New York  Finger Lakes
101              Red Oak Vineyard      87   20.0      New York  Finger Lakes
102           Yellow Dog Vineyard      87   20.0      New York  Finger Lakes
103  Single Vineyard Falaris Hill      87   18.0  Leyda Valley           NaN
104                        Nativo      87   16.0       Tuscany       Toscana

         region_2         taster_name taster_twitter_handle  \
100  Finger Lakes  Anna Lee C. Iijima                   NaN
101  Finger Lakes  Anna Lee C. Iijima                   NaN
102  Finger Lakes  Anna Lee C. Iijima                   NaN
103           NaN   Michael Schachner           @wineschach
104           NaN       Kerin O’Keefe          @kerinokeefe

                                                 title     variety  \
100             Ventosa 2015 Pinot Gris (Finger Lakes)  Pinot Gris
101  Lamoreaux Landing 2014 Red Oak Vineyard Riesli...    Riesling
102  Lamoreaux Landing 2014 Yellow Dog Vineyard Rie...    Riesling
103  Leyda 2015 Single Vineyard Falaris Hill Chardo...  Chardonnay
104             Madonna Alta 2014 Nativo Red (Toscana)   Red Blend

                winery
100            Ventosa
101  Lamoreaux Landing
102  Lamoreaux Landing
103              Leyda
104       Madonna Alta
     Unnamed: 0   country                                        description  \
200         200     Italy  Aromas of mature black-skinned berry, tobacco ...
201         201     Italy  Made with 60% Pinot Bianco, 30% Chardonnay and...
202         202    Israel  This wine features pleasing aromas of raspberr...
203         203  Portugal  A year in wood and 30 months in bottle before ...
204         204        US  This bottling belongs to a series of wines fro...

                  designation  points  price            province  \
200                   Riserva      90    NaN             Tuscany
201        Nova Domus Riserva      90   62.0  Northeastern Italy
202                       NaN      90   50.0        Judean Hills
203  Montes Claros Garrafeira      90   28.0            Alentejo
204                   Gesture      90   30.0          California

                   region_1       region_2    taster_name  \
200  Brunello di Montalcino            NaN  Kerin O’Keefe
201              Alto Adige            NaN  Kerin O’Keefe
202                     NaN            NaN  Mike DeSimone
203                     NaN            NaN     Roger Voss
204             Paso Robles  Central Coast  Matt Kettmann

    taster_twitter_handle                                              title  \
200          @kerinokeefe  Tenuta di Sesta 2011 Riserva  (Brunello di Mon...
201          @kerinokeefe  Terlan 2014 Nova Domus Riserva White (Alto Adige)
202        @worldwineguys                    Yatir 2011 Syrah (Judean Hills)
203            @vossroger  Adega Cooperativa de Borba 2012 Montes Claros ...
204         @mattkettmann           J. Lohr 2014 Gesture G-S-M (Paso Robles)

            variety                      winery
200      Sangiovese             Tenuta di Sesta
201     White Blend                      Terlan
202           Syrah                       Yatir
203  Portuguese Red  Adega Cooperativa de Borba
204           G-S-M                     J. Lohr
     Unnamed: 0 country                                        description  \
300         300      US  Soft, light in body and easy to drink, this Sa...
301         301      US  A good, clean, tart and lightly spicy all-stai...
302         302   Italy  This fresh Nebbiolo-based Roero from Cantina d...
303         303   Italy  Slightly disjointed at first, this Barolo with...
304         304   Italy  This aged expression from the Nizza subzone of...

          designation  points  price    province  \
300            Estate      87   28.0  California
301  Whiteline No Oak      87   14.0  Washington
302               NaN      87    NaN    Piedmont
303           4 Vigne      87   56.0    Piedmont
304          Vignassa      87    NaN    Piedmont

                           region_1         region_2   taster_name  \
300                     Napa Valley             Napa           NaN
301            Columbia Valley (WA)  Columbia Valley  Paul Gregutt
302                           Roero              NaN           NaN
303                          Barolo              NaN           NaN
304  Barbera d'Asti Superiore Nizza              NaN           NaN

    taster_twitter_handle                                              title  \
300                   NaN     Benessere 2007 Estate Sangiovese (Napa Valley)
301           @paulgwine   Buried Cane 2009 Whiteline No Oak Chardonnay (...
302                   NaN                   Cantina del Nebbiolo 2008  Roero
303                   NaN            Cascina Adelaide 2005 4 Vigne  (Barolo)
304                   NaN  Cascina La Ghersa 2004 Vignassa  (Barbera d'As...

        variety                winery
300  Sangiovese             Benessere
301  Chardonnay           Buried Cane
302    Nebbiolo  Cantina del Nebbiolo
303    Nebbiolo      Cascina Adelaide
304     Barbera     Cascina La Ghersa
     Unnamed: 0 country                                        description  \
400         400   Italy  Tonic and lean with a nearly transparent color...
401         401   Italy  This Extra Dry (slightly sweet) vintage Prosec...
402         402   Chile  Formerly doing business as “Shiraz,” this Syra...
403         403      US  Dry and acidic, this light-bodied wine has tar...
404         404      US  Smells funky, with sweaty leather aromas, alth...

               designation  points  price          province  \
400                   Brut      85   13.0       Italy Other
401  Millesimato Extra Dry      85   19.0            Veneto
402   Casa la Joya Reserve      85   11.0  Colchagua Valley
403          Le Bon Viveur      85   15.0        California
404    White Hawk Vineyard      85   45.0        California

                      region_1          region_2        taster_name  \
400                      Italy               NaN                NaN
401  Prosecco di Valdobbiadene               NaN                NaN
402                        NaN               NaN  Michael Schachner
403                 California  California Other                NaN
404       Santa Barbara County     Central Coast                NaN

    taster_twitter_handle                                              title  \
400                   NaN           Cantine Maschio NV Brut Prosecco (Italy)
401                   NaN  Val d'Oca 2008 Millesimato Extra Dry  (Prosecc...
402           @wineschach  Viña Bisquertt 2007 Casa la Joya Reserve Syrah...
403                   NaN      Vinavanti 2005 Le Bon Viveur Red (California)
404                   NaN  Vino V 2005 White Hawk Vineyard Syrah (Santa B...

       variety           winery
400   Prosecco  Cantine Maschio
401   Prosecco        Val d'Oca
402      Syrah   Viña Bisquertt
403  Red Blend        Vinavanti
404      Syrah           Vino V
     Unnamed: 0  country                                        description  \
500         500    Spain  Aromas of watermelon and a dusting of natural ...
501         501       US  A Verdelho with a taste of nuts—like Marcona a...
502         502  Austria  Deliciously perfumed, this is as light as a fe...
503         503       US  Sauvignon Blanc has been a consistent performe...
504         504   France  A simple but attractive Côtes du Rhône, with i...

              designation  points  price               province  \
500                Rosado      87   11.0         Northern Spain
501  Silvaspoons Vineyard      87   15.0             California
502               Muscato      87   18.0  Österreichischer Sekt
503                   NaN      87   19.0             California
504  Réserve Grand Veneur      87   15.0           Rhône Valley

                 region_1        region_2        taster_name  \
500                 Rioja             NaN  Michael Schachner
501                  Lodi  Central Valley     Virginie Boone
502                   NaN             NaN         Roger Voss
503  Russian River Valley          Sonoma                NaN
504        Côtes du Rhône             NaN     Joe Czerwinski

    taster_twitter_handle                                              title  \
500           @wineschach                   El Coto 2011 Rosado Rosé (Rioja)
501               @vboone  Fenestra 2010 Silvaspoons Vineyard Verdelho (L...
502            @vossroger  Gunter Triebaumer NV Muscato Moscato (Österrei...
503                   NaN  Hanna 2011 Sauvignon Blanc (Russian River Valley)
504                @JoeCz  Alain Jaume et Fils 2009 Réserve Grand Veneur ...

                   variety               winery
500                   Rosé              El Coto
501               Verdelho             Fenestra
502                Moscato    Gunter Triebaumer
503        Sauvignon Blanc                Hanna
504  Rhône-style Red Blend  Alain Jaume et Fils
     Unnamed: 0 country                                        description  \
600         600   Italy  Crisp and light with pretty mineral dustings b...
601         601  Mexico  Sauvignon Blanc is, in general, one of Baja's ...
602         602      US  There's plenty of ripe berry-cherry fruit, fin...
603         603      US  Ripe and luscious, this decadent Cabernet Fran...
604         604   Spain  Bright red-fruit aromas are matched by dry spi...

      designation  points  price            province  \
600      Le Marne      87   19.0            Piedmont
601  Viña Kristel      87   15.0  Valle de Guadalupe
602           NaN      87   69.0          California
603           NaN      87   36.0            New York
604  Reserva 1423      87   35.0      Northern Spain

                      region_1     region_2         taster_name  \
600                       Gavi          NaN                 NaN
601                        NaN          NaN   Michael Schachner
602         Oak Knoll District         Napa                 NaN
603  North Fork of Long Island  Long Island  Anna Lee C. Iijima
604                    Navarra          NaN   Michael Schachner

    taster_twitter_handle                                              title  \
600                   NaN              Michele Chiarlo 2011 Le Marne  (Gavi)
601           @wineschach  Monte Xanic 2012 Viña Kristel Sauvignon Blanc ...
602                   NaN  Paoletti 2010 Cabernet Sauvignon (Oak Knoll Di...
603                   NaN  Peconic Bay Winery 2010 Cabernet Franc (North ...
604           @wineschach  Príncipe de Viana 2008 Reserva 1423 Red (Navarra)

                variety              winery
600             Cortese     Michele Chiarlo
601     Sauvignon Blanc         Monte Xanic
602  Cabernet Sauvignon            Paoletti
603      Cabernet Franc  Peconic Bay Winery
604           Red Blend   Príncipe de Viana
     Unnamed: 0    country                                        description  \
700         700  Argentina  Intriguing aromas of lavender, hoja santa and ...
701         701     France  Always released after a further year's aging, ...
702         702     France  Produced by the owners of Châteauneuf-du-Pape ...
703         703     France  While the wine is really pale in color, it doe...
704         704     France  This rich and impressive wine has structure an...

    designation  points  price          province                   region_1  \
700         NaN      91   30.0  Mendoza Province                    Mendoza
701   Les Clans      91   65.0          Provence          Côtes de Provence
702         NaN      91   17.0          Provence          Côtes de Provence
703         NaN      91    NaN          Provence          Côtes de Provence
704         NaN      91   20.0          Provence  Coteaux d'Aix-en-Provence

    region_2        taster_name taster_twitter_handle  \
700      NaN  Michael Schachner           @wineschach
701      NaN         Roger Voss            @vossroger
702      NaN         Roger Voss            @vossroger
703      NaN         Roger Voss            @vossroger
704      NaN         Roger Voss            @vossroger

                                                 title  variety  \
700                  El Enemigo 2012 Bonarda (Mendoza)  Bonarda
701  Château d'Esclans 2013 Les Clans Rosé (Côtes d...     Rosé
702       Château Riotor 2014 Rosé (Côtes de Provence)     Rosé
703  Château Sainte Marguerite 2014 Rosé (Côtes de ...     Rosé
704  Château Vignelaure 2014 Rosé (Coteaux d'Aix-en...     Rosé

                        winery
700                 El Enemigo
701          Château d'Esclans
702             Château Riotor
703  Château Sainte Marguerite
704         Château Vignelaure
     Unnamed: 0 country                                        description  \
800         800      US  With black cherry, blueberry, milk chocolate a...
801         801      US  Made entirely from Syrah grown on its property...
802         802  France  This is a firm wine, balancing some solid tann...
803         803      US  Aromas of savory herbs, mineral, exotic spice ...
804         804      US  The aromas of mineral, spice, toast, yellow ap...

                  designation  points  price    province           region_1  \
800                       NaN      90   20.0  California  Santa Ynez Valley
801              Tawny Estate      90   50.0  California      Sonoma Valley
802              Le Griottier      90   22.0  Beaujolais           Juliénas
803  Upright Klipsun Vineyard      90   39.0  Washington       Red Mountain
804   Lola Evergreen Vineyard      90   35.0  Washington      Ancient Lakes

            region_2       taster_name taster_twitter_handle  \
800    Central Coast     Matt Kettmann         @mattkettmann
801           Sonoma    Virginie Boone               @vboone
802              NaN        Roger Voss            @vossroger
803  Columbia Valley  Sean P. Sullivan         @wawinereport
804  Columbia Valley  Sean P. Sullivan         @wawinereport

                                                 title             variety  \
800  Chessman 2014 Cabernet Sauvignon (Santa Ynez V...  Cabernet Sauvignon
801  Deerfield Ranch NV Tawny Estate Syrah (Sonoma ...               Syrah
802  Domaine Franck Besson 2014 Le Griottier  (Juli...               Gamay
803  Efeste 2013 Upright Klipsun Vineyard Merlot (R...              Merlot
804  Efeste 2014 Lola Evergreen Vineyard Chardonnay...          Chardonnay

                    winery
800               Chessman
801        Deerfield Ranch
802  Domaine Franck Besson
803                 Efeste
804                 Efeste
     Unnamed: 0   country                                        description  \
900         900     Spain  It has taken a few years but Morlanda has reac...
901         901  Portugal  A wood-aged white, spicy and ripe. It has just...
902         902        US  White lily, popcorn kernel, citrus spray and u...
903         903   Germany  Whiffs of smoke and nuts mingle into tart tang...
904         904     Italy  Aromas of leather, vineyard dust, dried violet...

                  designation  points  price   province           region_1  \
900                   Criança      90   48.0  Catalonia            Priorat
901            Reserva Branco      90   50.0      Douro                NaN
902  Reserve Bingham Vineyard      87   22.0      Texas  Texas High Plains
903                       NaN      87   10.0       Nahe                NaN
904                      Pajè      87   50.0   Piedmont         Barbaresco

    region_2         taster_name taster_twitter_handle  \
900      NaN   Michael Schachner           @wineschach
901      NaN          Roger Voss            @vossroger
902      NaN  Alexander Peartree                   NaN
903      NaN  Anna Lee C. Iijima                   NaN
904      NaN       Kerin O’Keefe          @kerinokeefe

                                                 title           variety  \
900                Morlanda 2007 Criança Red (Priorat)         Red Blend
901  Quinta do Vallado 2010 Reserva Branco White (D...  Portuguese White
902  Becker 2014 Reserve Bingham Vineyard Roussanne...         Roussanne
903                           Bex 2014 Riesling (Nahe)          Riesling
904                      Boffa 2013 Pajè  (Barbaresco)          Nebbiolo

                winery
900           Morlanda
901  Quinta do Vallado
902             Becker
903                Bex
904              Boffa
      Unnamed: 0 country                                        description  \
1000        1000      US  Arcane's Cab is stylistically apart from eithe...
1001        1001   Italy  Nerello Mascalese, a grape native to the volca...
1002        1002      US  Aromas of cherry, spice and mint lead into tar...
1003        1003  France  The richness of vintage 2003  shows in this wi...
1004        1004  France  Full, firm white wine that gives good green fr...

          designation  points  price           province           region_1  \
1000              NaN      88   24.0             Oregon       Rogue Valley
1001   Il Monovitigno      88   41.0  Sicily & Sardinia               Etna
1002      First Class      88   60.0             Oregon  Willamette Valley
1003  Vieilles Vignes      88   26.0   Southwest France          Montravel
1004       Marjolaine      88   25.0   Southwest France          Montravel

               region_2   taster_name taster_twitter_handle  \
1000    Southern Oregon  Paul Gregutt           @paulgwine