### Loading data into pandas

In [2]:
import pandas as pd
df = pd.read_csv('pokemon_data.csv')
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False

In [3]:
df. tail()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True

In [4]:
df_xlsx=pd.read_excel('pokemon.xlsx')
print(df_xlsx.head())
# for txt files too use pd.read_csv()

   #                   Name Type 1  Type 2  HP  Attack  Defense  Sp. Atk  \
0  1              Bulbasaur  Grass  Poison  45      49       49       65
1  2                Ivysaur  Grass  Poison  60      62       63       80
2  3               Venusaur  Grass  Poison  80      82       83      100
3  3  VenusaurMega Venusaur  Grass  Poison  80     100      123      122
4  4             Charmander   Fire     NaN  39      52       43       60

   Sp. Def  Speed  Generation  Legendary
0       65     45           1      False
1       80     60           1      False
2      100     80           1      False
3      120     80           1      False
4       50     65           1      False

### Reading data in pandas

In [5]:
# To read headers or field name
print(df.columns)

Index(['#', 'Name', 'Type 1', 'Type 2', 'HP', 'Attack', 'Defense', 'Sp. Atk',
       'Sp. Def', 'Speed', 'Generation', 'Legendary'],
      dtype='object')

In [6]:
#To read each / specific columns
# print(df['Name'].head(5)) OR
print(df['Name'][0:5])  #To access single column

0                Bulbasaur
1                  Ivysaur
2                 Venusaur
3    VenusaurMega Venusaur
4               Charmander
Name: Name, dtype: object

In [7]:
print(df[['Name','Type 1','Type 2']][0:5])  #To access multiple columns 

# read each row
print(df.iloc[1])

                    Name Type 1  Type 2
0              Bulbasaur  Grass  Poison
1                Ivysaur  Grass  Poison
2               Venusaur  Grass  Poison
3  VenusaurMega Venusaur  Grass  Poison
4             Charmander   Fire     NaN
#                   2
Name          Ivysaur
Type 1          Grass
Type 2         Poison
HP                 60
Attack             62
Defense            63
Sp. Atk            80
Sp. Def            80
Speed              60
Generation          1
Legendary       False
Name: 1, dtype: object

In [8]:
# To read  multiple rows
# print(df.iloc[0:4])

In [9]:
# to read a specific location(R,C)
print(df.iloc[2,1])

Venusaur

In [10]:
for index,row in df.iloc[0:4].iterrows():
    print(index,row['Name'])   #To print name on each index 0 to 3

0 Bulbasaur
1 Ivysaur
2 Venusaur
3 VenusaurMega Venusaur

In [11]:
df.loc[1] #Prints index 1

df.loc[1:3] #Prints index 1 and 2 including 3 too 
# In case of iloc it excludes 3

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False

In [12]:
df.loc[df['Type 1']=='Fire'].head() #prints 5 rows whose type 1 is fire

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,58,64,58,80,65,80,1,False
6,6,Charizard,Fire,Flying,78,84,78,109,85,100,1,False
7,6,CharizardMega Charizard X,Fire,Dragon,78,130,111,130,85,100,1,False
8,6,CharizardMega Charizard Y,Fire,Flying,78,104,78,159,115,100,1,False

### Sorting or describing data

In [13]:
df.describe() #It will print the statistics related to data such count,mean,std,min,

,#,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation
count,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.000000,800.00000
mean,362.813750,69.258750,79.001250,73.842500,72.820000,71.902500,68.277500,3.32375
std,208.343798,25.534669,32.457366,31.183501,32.722294,27.828916,29.060474,1.66129
min,1.000000,1.000000,5.000000,5.000000,10.000000,20.000000,5.000000,1.00000
25%,184.750000,50.000000,55.000000,50.000000,49.750000,50.000000,45.000000,2.00000
50%,364.500000,65.000000,75.000000,70.000000,65.000000,70.000000,65.000000,3.00000
75%,539.250000,80.000000,100.000000,90.000000,95.000000,90.000000,90.000000,5.00000
max,721.000000,255.000000,190.000000,230.000000,194.000000,230.000000,180.000000,6.00000

In [14]:
print(df['HP'].mean()) # calculate mean of hp individually

69.25875

In [15]:
df.sort_values('Name',ascending=False).head() #Sorts in descending order.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False

In [16]:
df.sort_values(['Name','Type 1'],ascending=[1,0]) #sorts name in ascending and Type 1 in descending order.

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
510,460,Abomasnow,Grass,Ice,90,92,75,92,85,60,4,False
511,460,AbomasnowMega Abomasnow,Grass,Ice,90,132,105,132,105,30,4,False
68,63,Abra,Psychic,NaN,25,20,15,105,55,90,1,False
392,359,Absol,Dark,NaN,65,130,60,75,60,75,3,False
393,359,AbsolMega Absol,Dark,NaN,65,150,60,115,60,115,3,False
...,...,...,...,...,...,...,...,...,...,...,...,...
632,571,Zoroark,Dark,NaN,60,105,60,120,60,105,5,False
631,570,Zorua,Dark,NaN,40,65,40,80,40,65,5,False
46,41,Zubat,Poison,Flying,40,45,35,30,40,55,1,False
695,634,Zweilous,Dark,Dragon,72,85,70,65,70,58,5,False
794,718,Zygarde50% Forme,Dragon,Ground,108,100,121,81,95,95,6,True

### Making changes to the data

In [17]:
# Add the total column on the given table
df['Total']=df['HP']+df['Attack']+df['Defense']+df['Sp. Atk']+df['Sp. Def']+df['Speed']
df.head()

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309

In [18]:
df.sort_index(ascending=False) 

df

,#,Name,Type 1,Type 2,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary,Total
0,1,Bulbasaur,Grass,Poison,45,49,49,65,65,45,1,False,318
1,2,Ivysaur,Grass,Poison,60,62,63,80,80,60,1,False,405
2,3,Venusaur,Grass,Poison,80,82,83,100,100,80,1,False,525
3,3,VenusaurMega Venusaur,Grass,Poison,80,100,123,122,120,80,1,False,625
4,4,Charmander,Fire,NaN,39,52,43,60,50,65,1,False,309
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,50,100,150,100,150,50,6,True,600
796,719,DiancieMega Diancie,Rock,Fairy,50,160,110,160,110,110,6,True,700
797,720,HoopaHoopa Confined,Psychic,Ghost,80,110,60,150,130,70,6,True,600
798,720,HoopaHoopa Unbound,Psychic,Dark,80,160,60,170,130,80,6,True,680
799,721,Volcanion,Fire,Water,80,110,120,130,90,70,6,True,600

In [19]:
df['Total']=df.iloc[:,4:10].sum(axis=1)
cols=list(df.columns.values)
df=df[cols[0:4]+[cols[-1]]+cols[4:12]] #swaps the column or rearranging columns
df.head(5)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False

### Saving our data (Exporting into desired format)

In [20]:
# df.to_csv('modified.csv',index=False) 
# Changing the file to csv

# df.to_excel('modified.xlsx',index=False) 
# changing to excel

df.to_csv('modified.txt',index=False,sep='\t')

### Filtering Data

In [21]:
new_df=df.loc[(df['Type 1']=='Grass') & (df['Type 2']=='Poison')].head(10)

df.loc[(df['Type 1']=='Grass') | (df['Type 2']=='Poison')].head()

print(new_df)

     #                   Name Type 1  Type 2  Total  HP  Attack  Defense  \
0    1              Bulbasaur  Grass  Poison    318  45      49       49
1    2                Ivysaur  Grass  Poison    405  60      62       63
2    3               Venusaur  Grass  Poison    525  80      82       83
3    3  VenusaurMega Venusaur  Grass  Poison    625  80     100      123
48  43                 Oddish  Grass  Poison    320  45      50       55
49  44                  Gloom  Grass  Poison    395  60      65       70
50  45              Vileplume  Grass  Poison    490  75      80       85
75  69             Bellsprout  Grass  Poison    300  50      75       35
76  70             Weepinbell  Grass  Poison    390  65      90       50
77  71             Victreebel  Grass  Poison    490  80     105       65

    Sp. Atk  Sp. Def  Speed  Generation  Legendary
0        65       65     45           1      False
1        80       80     60           1      False
2       100      100     80           1      False
3       122      120     80           1      False
48       75       65     30           1      False
49       85       75     40           1      False
50      110       90     50           1      False
75       70       30     40           1      False
76       85       45     55           1      False
77      100       70     70           1      False

In [22]:
new_df=new_df.reset_index(drop=True,inplace=True)  

print(new_df)

None

In [23]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 800 entries, 0 to 799
Data columns (total 13 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   #           800 non-null    int64
 1   Name        800 non-null    object
 2   Type 1      800 non-null    object
 3   Type 2      414 non-null    object
 4   Total       800 non-null    int64
 5   HP          800 non-null    int64
 6   Attack      800 non-null    int64
 7   Defense     800 non-null    int64
 8   Sp. Atk     800 non-null    int64
 9   Sp. Def     800 non-null    int64
 10  Speed       800 non-null    int64
 11  Generation  800 non-null    int64
 12  Legendary   800 non-null    bool
dtypes: bool(1), int64(9), object(3)
memory usage: 75.9+ KB

In [24]:
# df.loc[df['Name'].str.contains('Mega')]
#Displays the rows data whose name contains substring mega

df.loc[~df['Name'].str.contains('Mega')] #displays the one which doesnt include mega string

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
5,5,Charmeleon,Fire,NaN,405,58,64,58,80,65,80,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
794,718,Zygarde50% Forme,Dragon,Ground,600,108,100,121,81,95,95,6,True
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [25]:
import re
""" RE is Fire|Grass , since regex=True it will look for the text that can be either grass or fire
 but if regex=False it will look for exact (Fire|Grass) ie fire with or symbol followed by grass."""
# Here flags=re.I means it will ignore upper & lower case of string while searching.

' RE is Fire|Grass , since regex=True it will look for the text that can be either grass or fire\n but if regex=False it will look for exact (Fire|Grass) ie fire with or symbol followed by grass.'

In [26]:
# df.loc[df['Type 1'].str.contains('Fire|Grass',flags=re.I,regex=True)]
df.loc[df['Type 1'].str.contains('Fire|Grass',flags=re.I,regex=False)]

Empty DataFrame
Columns: [#, Name, Type 1, Type 2, Total, HP, Attack, Defense, Sp. Atk, Sp. Def, Speed, Generation, Legendary]
Index: []

In [27]:
df.loc[df['Name'].str.startswith('B')]

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
11,9,Blastoise,Water,NaN,530,79,83,100,85,105,78,1,False
12,9,BlastoiseMega Blastoise,Water,NaN,630,79,103,120,135,115,78,1,False
15,12,Butterfree,Bug,Flying,395,60,45,50,90,80,70,1,False
18,15,Beedrill,Bug,Poison,395,65,90,40,45,80,75,1,False
19,15,BeedrillMega Beedrill,Bug,Poison,495,65,150,40,15,80,145,1,False
75,69,Bellsprout,Grass,Poison,300,50,75,35,70,30,40,1,False
167,153,Bayleef,Grass,NaN,405,60,62,80,63,80,60,2,False
197,182,Bellossom,Grass,NaN,490,75,80,95,90,100,50,2,False
261,242,Blissey,Normal,NaN,540,255,10,10,75,135,55,2,False
278,257,Blaziken,Fire,Fighting,530,80,120,70,110,70,80,3,False
279,257,BlazikenMega Blaziken,Fire,Fighting,630,80,160,80,130,80,100,3,False
290,267,Beautifly,Bug,Flying,395,60,70,50,100,50,65,3,False
310,286,Breloom,Grass,Fighting,460,60,130,80,60,60,70,3,False
371,339,Barboach,Water,Ground,288,50,48,43,46,41,60,3,False
375,343,Baltoy,Ground,Psychic,300,40,40,55,40,70,55,3,False
386,354,Banette,Ghost,NaN,455,64,115,65,83,63,65,3,False
387,354,BanetteMega Banette,Ghost,NaN,555,64,165,75,93,83,75,3,False
406,371,Bagon,Dragon,NaN,300,45,75,60,40,30,50,3,False
410,374,Beldum,Steel,Psychic,300,40,55,80,35,60,30,3,False
444,399,Bidoof,Normal,NaN,250,59,45,40,35,40,31,4,False
445,400,Bibarel,Normal,Water,410,79,85,60,55,60,71,4,False
451,406,Budew,Grass,Poison,280,40,30,35,50,70,55,4,False
456,411,Bastiodon,Rock,Steel,495,60,52,168,47,138,30,4,False
457,412,Burmy,Bug,NaN,224,40,29,45,29,45,36,4,False
465,418,Buizel,Water,NaN,330,55,65,35,60,30,85,4,False
474,427,Buneary,Normal,NaN,350,55,66,44,44,56,85,4,False
484,436,Bronzor,Steel,Psychic,300,57,24,86,24,86,23,4,False
485,437,Bronzong,Steel,Psychic,500,67,89,116,79,116,33,4,False
486,438,Bonsly,Rock,NaN,290,50,80,95,10,45,10,4,False
581,522,Blitzle,Electric,NaN,295,45,60,32,50,32,76,5,False
584,525,Boldore,Rock,NaN,390,70,105,105,50,40,20,5,False
610,550,Basculin,Water,NaN,460,70,92,65,80,55,98,5,False
667,606,Beheeyem,Psychic,NaN,485,75,75,75,125,95,40,5,False
675,614,Beartic,Ice,NaN,485,95,110,80,70,80,50,5,False
686,625,Bisharp,Dark,Steel,490,65,125,100,60,70,70,5,False
687,626,Bouffalant,Normal,NaN,490,95,110,95,40,95,55,5,False
689,628,Braviary,Normal,Flying,510,100,123,75,57,75,80,5,False
722,654,Braixen,Fire,NaN,409,59,59,58,90,70,73,6,False
727,659,Bunnelby,Normal,NaN,237,38,36,38,32,36,57,6,False
758,688,Binacle,Rock,Water,306,42,52,67,39,56,50,6,False
759,689,Barbaracle,Rock,Water,500,72,105,115,54,86,68,6,False
788,712,Bergmite,Ice,NaN,304,55,69,85,32,35,28,6,False

In [28]:
df.loc[df['Name'].str.contains('^pi[a-z]*',flags=re.I,regex=True)] #print names that starts with pi

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
20,16,Pidgey,Normal,Flying,251,40,45,40,35,35,56,1,False
21,17,Pidgeotto,Normal,Flying,349,63,60,55,50,50,71,1,False
22,18,Pidgeot,Normal,Flying,479,83,80,75,70,70,101,1,False
23,18,PidgeotMega Pidgeot,Normal,Flying,579,83,80,80,135,80,121,1,False
30,25,Pikachu,Electric,NaN,320,35,55,40,50,50,90,1,False
136,127,Pinsir,Bug,NaN,500,65,125,100,55,70,85,1,False
137,127,PinsirMega Pinsir,Bug,Flying,600,65,155,120,65,90,105,1,False
186,172,Pichu,Electric,NaN,205,20,40,15,35,35,60,2,False
219,204,Pineco,Bug,NaN,290,50,65,90,35,35,15,2,False
239,221,Piloswine,Ice,Ground,450,100,100,80,60,60,50,2,False
438,393,Piplup,Water,NaN,314,53,51,53,61,56,40,4,False
558,499,Pignite,Fire,Fighting,418,90,93,55,70,55,55,5,False
578,519,Pidove,Normal,Flying,264,50,55,50,36,30,43,5,False

### Conditional changes

In [29]:
df.loc[df['Type 1']=='Fire','Type 1']='Flamer'
df

df.loc[df['Total']>500,['Generation','Legendary']]= ['TEST1','TEST2'] 
#This will change the value of Generation to TEST1 and legendary to TEST2 if the Total value is greater than 500

df

C:\Users\Dell\AppData\Local\Temp\ipykernel_10772\2904001607.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'TEST1' has dtype incompatible with int64, please explicitly cast to a compatible dtype first.
  df.loc[df['Total']>500,['Generation','Legendary']]= ['TEST1','TEST2']
C:\Users\Dell\AppData\Local\Temp\ipykernel_10772\2904001607.py:4: FutureWarning: Setting an item of incompatible dtype is deprecated and will raise an error in a future version of pandas. Value 'TEST2' has dtype incompatible with bool, please explicitly cast to a compatible dtype first.
  df.loc[df['Total']>500,['Generation','Legendary']]= ['TEST1','TEST2']

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,TEST1,TEST2
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,TEST1,TEST2
4,4,Charmander,Flamer,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,TEST1,TEST2
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,TEST1,TEST2
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,TEST1,TEST2
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,TEST1,TEST2
799,721,Volcanion,Flamer,Water,600,80,110,120,130,90,70,TEST1,TEST2

### Aggrerate Statistics(Groupby)

In [30]:
df = pd.read_csv('modified.csv')
# df.groupby(['Type 1']).mean(numeric_only=True).sort_values('Defense',ascending=False)

df.groupby('Type 1').sum(numeric_only=True).head()

df.groupby('Type 1').count() 
df.groupby(['Type 1','Type 2']).count()

                  #  Name  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
Type 1 Type 2
Bug    Electric   2     2      2   2       2        2        2        2
       Fighting   2     2      2   2       2        2        2        2
       Fire       2     2      2   2       2        2        2        2
       Flying    14    14     14  14      14       14       14       14
       Ghost      1     1      1   1       1        1        1        1
...              ..   ...    ...  ..     ...      ...      ...      ...
Water  Ice        3     3      3   3       3        3        3        3
       Poison     3     3      3   3       3        3        3        3
       Psychic    5     5      5   5       5        5        5        5
       Rock       4     4      4   4       4        4        4        4
       Steel      1     1      1   1       1        1        1        1

                 Speed  Generation  Legendary
Type 1 Type 2
Bug    Electric      2           2          2
       Fighting      2           2          2
       Fire          2           2          2
       Flying       14          14         14
       Ghost         1           1          1
...                ...         ...        ...
Water  Ice           3           3          3
       Poison        3           3          3
       Psychic       5           5          5
       Rock          4           4          4
       Steel         1           1          1

[136 rows x 11 columns]

### Working with large amounts of data

In [99]:
# for df in pd.read_csv('modified.csv',chunksize=5):
#     print("CHUNK DF")
#     print(df)

### Handling Missing Data

In [32]:
df.isna()

import numpy as np
d = {'First Score': [100, 90, np.nan, 95],
        'Second Score': [30, np.nan, 56, np.nan],
        'Third Score': [np.nan, 40, 80, 98]}
newd = pd.DataFrame(d)


newd

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0           NaN         40.0
2          NaN          56.0         80.0
3         95.0           NaN         98.0

In [33]:
#### Handling missing data

newd.isnull().sum() #gives the no of null elements in all columns

print(pd.isnull(newd['First Score'])) #checks if first row each indexes are null or not for first score


newd.notnull() #checks the not null condition i.e. returns true if notnull else false

0    False
1    False
2     True
3    False
Name: First Score, dtype: bool

   First Score  Second Score  Third Score
0         True          True        False
1         True         False         True
2        False          True         True
3         True         False         True

### Filling missing values

In [34]:
newd.fillna(0)

   First Score  Second Score  Third Score
0        100.0          30.0          0.0
1         90.0           0.0         40.0
2          0.0          56.0         80.0
3         95.0           0.0         98.0

In [35]:
newd.fillna(method='pad') #Fills the missing value with previous value in same column

C:\Users\Dell\AppData\Local\Temp\ipykernel_10772\1979251446.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newd.fillna(method='pad') #Fills the missing value with previous value in same column

   First Score  Second Score  Third Score
0        100.0          30.0          NaN
1         90.0          30.0         40.0
2         90.0          56.0         80.0
3         95.0          56.0         98.0

In [36]:
newd.fillna(method='bfill') #fills missing value with next value in same column

# newd['First Score'].fillna('Not Given')
newd['Second Score'].fillna('Not Given')

C:\Users\Dell\AppData\Local\Temp\ipykernel_10772\3083788128.py:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  newd.fillna(method='bfill') #fills missing value with next value in same column

0         30.0
1    Not Given
2         56.0
3    Not Given
Name: Second Score, dtype: object

In [37]:
newd=newd.replace(to_replace=np.nan,value=-1)

newd

   First Score  Second Score  Third Score
0        100.0          30.0         -1.0
1         90.0          -1.0         40.0
2         -1.0          56.0         80.0
3         95.0          -1.0         98.0

In [38]:
df_new = pd.DataFrame({"A": [12, 4, 5, None, 1], 
                   "B": [None, 2, 54, 3, None], 
                   "C": [20, 16, None, 3, 8], 
                   "D": [14, 3, None, None, 6]})  
print(df_new)

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   NaN   NaN
3   NaN   3.0   3.0   NaN
4   1.0   NaN   8.0   6.0

In [39]:
df_new.interpolate(method='linear',limit_direction='forward')

      A     B     C     D
0  12.0   NaN  20.0  14.0
1   4.0   2.0  16.0   3.0
2   5.0  54.0   9.5   4.0
3   3.0   3.0   3.0   5.0
4   1.0   3.0   8.0   6.0

### Dropping Missing values in pandas

In [40]:
df_new.dropna() #Drops the row that consist of nan values.

     A    B     C    D
1  4.0  2.0  16.0  3.0

#### Dropping rows with all null values

In [41]:
df_new.iloc[0]=[np.nan,np.nan,np.nan,np.nan]

df_new

df_new.dropna(how='all') #Removes index 0 where all columns at index 0's is NaN

     A     B     C    D
1  4.0   2.0  16.0  3.0
2  5.0  54.0   NaN  NaN
3  NaN   3.0   3.0  NaN
4  1.0   NaN   8.0  6.0

#### Dropping columns with at least one null value

In [42]:
df_new.dropna(axis=1) #since all columns contains at least one missing value all columns are dropped.

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

### Dropping rows with missing values in csv file
##### df=df.dropna(axis=0,how='any')

### GROUPING
##### It allows us to group or organize data into categories and compute value for each group

In [43]:
df.head()

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In [44]:
res=df.groupby('Type 1')['HP'].sum()
res

Type 1
Fire        80
Psychic    160
Rock       100
Name: HP, dtype: int64

In [45]:
print(df.groupby(['Name','Type 2']).groups) #groups gives the alphabetical order wise name,type2 and index

{('Diancie', 'Fairy'): [795], ('DiancieMega Diancie', 'Fairy'): [796], ('HoopaHoopa Confined', 'Ghost'): [797], ('HoopaHoopa Unbound', 'Dark'): [798], ('Volcanion', 'Water'): [799]}

In [46]:
print(df.groupby('Type 2')['Speed'].sum()) # groups by type2 and give the sum of speed of various types

Type 2
Dark      80
Fairy    160
Ghost     70
Water     70
Name: Speed, dtype: int64

In [47]:
print(df.groupby('Type 2')['Attack'].mean())

Type 2
Dark     160.0
Fairy    130.0
Ghost    110.0
Water    110.0
Name: Attack, dtype: float64

In [48]:
grp=df.groupby('Name')
grp.get_group('HoopaHoopa Confined')

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True

In [49]:
for name,group in grp:
    print(name)
    print(group)

Diancie
       #     Name Type 1 Type 2  Total  HP  Attack  Defense  Sp. Atk  Sp. Def  \
795  719  Diancie   Rock  Fairy    600  50     100      150      100      150

     Speed  Generation  Legendary
795     50           6       True
DiancieMega Diancie
       #                 Name Type 1 Type 2  Total  HP  Attack  Defense  \
796  719  DiancieMega Diancie   Rock  Fairy    700  50     160      110

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
796      160      110    110           6       True
HoopaHoopa Confined
       #                 Name   Type 1 Type 2  Total  HP  Attack  Defense  \
797  720  HoopaHoopa Confined  Psychic  Ghost    600  80     110       60

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
797      150      130     70           6       True
HoopaHoopa Unbound
       #                Name   Type 1 Type 2  Total  HP  Attack  Defense  \
798  720  HoopaHoopa Unbound  Psychic   Dark    680  80     160       60

     Sp. Atk  Sp. Def  Speed  Generation  Legendary
798      170      130     80           6       True
Volcanion
       #       Name Type 1 Type 2  Total  HP  Attack  Defense  Sp. Atk  \
799  721  Volcanion   Fire  Water    600  80     110      120      130

     Sp. Def  Speed  Generation  Legendary
799       90     70           6       True

#### AGGREGATION

In [50]:
grp1=df.groupby('Type 1')
grp1['Total'].aggregate(np.sum)

C:\Users\Dell\AppData\Local\Temp\ipykernel_10772\1388764023.py:2: FutureWarning: The provided callable <function sum at 0x00000284A4ADAB60> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp1['Total'].aggregate(np.sum)

Type 1
Fire        600
Psychic    1280
Rock       1300
Name: Total, dtype: int64

In [51]:
#finding all sum,mean,std
grp2=df.groupby('Type 2')
grp2['Total'].agg([np.sum,np.mean,np.std])

C:\Users\Dell\AppData\Local\Temp\ipykernel_10772\3323402757.py:3: FutureWarning: The provided callable <function sum at 0x00000284A4ADAB60> is currently using SeriesGroupBy.sum. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "sum" instead.
  grp2['Total'].agg([np.sum,np.mean,np.std])
C:\Users\Dell\AppData\Local\Temp\ipykernel_10772\3323402757.py:3: FutureWarning: The provided callable <function mean at 0x00000284A4ADBF60> is currently using SeriesGroupBy.mean. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "mean" instead.
  grp2['Total'].agg([np.sum,np.mean,np.std])
C:\Users\Dell\AppData\Local\Temp\ipykernel_10772\3323402757.py:3: FutureWarning: The provided callable <function std at 0x00000284A4AE40E0> is currently using SeriesGroupBy.std. In a future version of pandas, the provided callable will be used directly. To keep current behavior pass the string "std" instead.
  grp2['Total'].agg([np.sum,np.mean,np.std])

         sum   mean        std
Type 2
Dark     680  680.0        NaN
Fairy   1300  650.0  70.710678
Ghost    600  600.0        NaN
Water    600  600.0        NaN

In [52]:
#finding,mean,max,count using agg
df.groupby("Type 2").agg(
    avg_Total=("Total", "mean"),
    max_total=("Total", "max"),
    count=("Total", "count")
)

        avg_Total  max_total  count
Type 2
Dark        680.0        680      1
Fairy       650.0        700      2
Ghost       600.0        600      1
Water       600.0        600      1

In [53]:
grp3=df.groupby('Type 1')
grp3.filter(lambda x:len(x)>=2)

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True

In [54]:
import pandas as pd

data1 = pd.DataFrame({'Name': ['Jai', 'Princi', 'Gaurav', 'Anuj'],
         'Age': [27, 24, 22, 32],
         'Address': ['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
         'Qualification': ['Msc', 'MA', 'MCA', 'Phd'],
         'Mobile No': [97, 91, 58, 76]})

data2 = pd.DataFrame({'Name': ['Gaurav', 'Anuj', 'Dhiraj', 'Hitesh'],
         'Age': [22, 32, 12, 52],
         'Address': ['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
         'Qualification': ['MCA', 'Phd', 'Bcom', 'B.hons'],
         'Salary': [1000, 2000, 3000, 4000]})

#### Concatenating dataframes

In [55]:
frames = [data1,data2]
res=pd.concat(frames)
res

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc       97.0     NaN
1  Princi   24     Kanpur            MA       91.0     NaN
2  Gaurav   22  Allahabad           MCA       58.0     NaN
3    Anuj   32    Kannuaj           Phd       76.0     NaN
0  Gaurav   22  Allahabad           MCA        NaN  1000.0
1    Anuj   32    Kannuaj           Phd        NaN  2000.0
2  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
3  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [56]:
res1 = pd.concat(frames, keys=['x', 'y'])
res1

       Name  Age    Address Qualification  Mobile No  Salary
x 0     Jai   27     Nagpur           Msc       97.0     NaN
  1  Princi   24     Kanpur            MA       91.0     NaN
  2  Gaurav   22  Allahabad           MCA       58.0     NaN
  3    Anuj   32    Kannuaj           Phd       76.0     NaN
y 0  Gaurav   22  Allahabad           MCA        NaN  1000.0
  1    Anuj   32    Kannuaj           Phd        NaN  2000.0
  2  Dhiraj   12  Allahabad          Bcom        NaN  3000.0
  3  Hitesh   52    Kannuaj        B.hons        NaN  4000.0

In [57]:
res2 = pd.concat([data1,data2],axis=1,join='inner')
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27,Nagpur,Msc,97,Gaurav,22,Allahabad,MCA,1000
1,Princi,24,Kanpur,MA,91,Anuj,32,Kannuaj,Phd,2000
2,Gaurav,22,Allahabad,MCA,58,Dhiraj,12,Allahabad,Bcom,3000
3,Anuj,32,Kannuaj,Phd,76,Hitesh,52,Kannuaj,B.hons,4000

In [58]:
res2 = pd.concat([data1,data2],axis=1,sort=True)
res2

,Name,Age,Address,Qualification,Mobile No,Name,Age,Address,Qualification,Salary
0,Jai,27,Nagpur,Msc,97,Gaurav,22,Allahabad,MCA,1000
1,Princi,24,Kanpur,MA,91,Anuj,32,Kannuaj,Phd,2000
2,Gaurav,22,Allahabad,MCA,58,Dhiraj,12,Allahabad,Bcom,3000
3,Anuj,32,Kannuaj,Phd,76,Hitesh,52,Kannuaj,B.hons,4000

In [59]:
# concatenating by ignoring index
res2 = pd.concat([data1,data2],axis=1,ignore_index=True)
res2

        0   1          2    3   4       5   6          7       8     9
0     Jai  27     Nagpur  Msc  97  Gaurav  22  Allahabad     MCA  1000
1  Princi  24     Kanpur   MA  91    Anuj  32    Kannuaj     Phd  2000
2  Gaurav  22  Allahabad  MCA  58  Dhiraj  12  Allahabad    Bcom  3000
3    Anuj  32    Kannuaj  Phd  76  Hitesh  52    Kannuaj  B.hons  4000

#### Concatenating Dataframe and series

In [60]:
S1 = pd.Series([1000,2000,3000,4000],name='Salary')
S1

0    1000
1    2000
2    3000
3    4000
Name: Salary, dtype: int64

In [61]:
res3 = pd.concat([data1,S1],axis=1)
res3

     Name  Age    Address Qualification  Mobile No  Salary
0     Jai   27     Nagpur           Msc         97    1000
1  Princi   24     Kanpur            MA         91    2000
2  Gaurav   22  Allahabad           MCA         58    3000
3    Anuj   32    Kannuaj           Phd         76    4000

## Merging Dataframe

### We can merge dataframes based on common column by using "on" argument.

In [62]:

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key    Name  Age
0  K0     Jai   27
1  K1  Princi   24
2  K2  Gaurav   22
3  K3    Anuj   32

   key    Address Qualification
0  K0     Nagpur         Btech
1  K1     Kanpur           B.A
2  K2  Allahabad          Bcom
3  K3    Kannuaj        B.hons

In [63]:
mer_result=pd.merge(df,df1,on='key') #It merges on the basis of key column
mer_result

  key    Name  Age    Address Qualification
0  K0     Jai   27     Nagpur         Btech
1  K1  Princi   24     Kanpur           B.A
2  K2  Gaurav   22  Allahabad          Bcom
3  K3    Anuj   32    Kannuaj        B.hons

In [64]:
import pandas as pd

data1 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K1', 'K0', 'K1'],
         'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],}

data2 = {'key': ['K0', 'K1', 'K2', 'K3'],
         'key1': ['K0', 'K0', 'K0', 'K0'],
         'Address':['Nagpur', 'Kanpur', 'Allahabad', 'Kannuaj'],
        'Qualification':['Btech', 'B.A', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2)


print(df, "\n\n", df1)

  key key1    Name  Age
0  K0   K0     Jai   27
1  K1   K1  Princi   24
2  K2   K0  Gaurav   22
3  K3   K1    Anuj   32

   key key1    Address Qualification
0  K0   K0     Nagpur         Btech
1  K1   K0     Kanpur           B.A
2  K2   K0  Allahabad          Bcom
3  K3   K0    Kannuaj        B.hons

In [65]:
res4=pd.merge(df,df1,on=['key','key1']) #It merges on the basis of multiple column and gives only the data whose keys match
res4

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K2   K0  Gaurav   22  Allahabad          Bcom

In [66]:
# We can join using how method, left outer,right outer,full outer,inner join

In [67]:
res5 = pd.merge(df,df1,how='left',on=['key','key1'])
res5

  key key1    Name  Age    Address Qualification
0  K0   K0     Jai   27     Nagpur         Btech
1  K1   K1  Princi   24        NaN           NaN
2  K2   K0  Gaurav   22  Allahabad          Bcom
3  K3   K1    Anuj   32        NaN           NaN

### Joining Dataframes

In [68]:

data1 = {'Name':['Jai', 'Princi', 'Gaurav', 'Anuj'],
        'Age':[27, 24, 22, 32],
        'Key':['K0', 'K1', 'K2', 'K3']}

data2 = {'Address':['Allahabad', 'Kannuaj', 'Allahabad', 'Kannuaj'],
        'Qualification':['MCA', 'Phd', 'Bcom', 'B.hons']}

df = pd.DataFrame(data1)

df1 = pd.DataFrame(data2, index=['K0', 'K2', 'K3', 'K4'])


print(df, "\n\n", df1)

     Name  Age Key
0     Jai   27  K0
1  Princi   24  K1
2  Gaurav   22  K2
3    Anuj   32  K3

       Address Qualification
K0  Allahabad           MCA
K2    Kannuaj           Phd
K3  Allahabad          Bcom
K4    Kannuaj        B.hons

In [69]:
res=df.join(df1)
res

     Name  Age Key Address Qualification
0     Jai   27  K0     NaN           NaN
1  Princi   24  K1     NaN           NaN
2  Gaurav   22  K2     NaN           NaN
3    Anuj   32  K3     NaN           NaN

In [70]:
res=df.join(df1,on='Key')
res

     Name  Age Key    Address Qualification
0     Jai   27  K0  Allahabad           MCA
1  Princi   24  K1        NaN           NaN
2  Gaurav   22  K2    Kannuaj           Phd
3    Anuj   32  K3  Allahabad          Bcom

In [71]:
!git add .

warning: in the working copy of '.ipynb_checkpoints/pandaspractice-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'pandaspractice.ipynb', LF will be replaced by CRLF the next time Git touches it

In [72]:
!git commit -m "Add merge and concat feature"

[main ffe4222] Add merge and concat feature
 2 files changed, 105036 insertions(+), 145 deletions(-)

In [73]:
!git push origin

To https://github.com/binita21/pandas.git
   ad04088..ffe4222  main -> main

In [74]:
a = pd.DataFrame({
    'i1' : [1,2,3,4,5],
    'val' : ['a','b','c','d','e']
})
b = pd.DataFrame({
    'i1' : [1,2,9,8,5],
    'val' : ['p','q','r','s','t']
})

In [75]:
join_res=pd.merge(a,b,how='inner',on='i1')
join_res

   i1 val_x val_y
0   1     a     p
1   2     b     q
2   5     e     t

In [76]:
join_res=pd.merge(a,b,how='left',on='i1')
join_res

   i1 val_x val_y
0   1     a     p
1   2     b     q
2   3     c   NaN
3   4     d   NaN
4   5     e     t

In [77]:
join_res=pd.merge(a,b,how='right',on='i1')
join_res

   i1 val_x val_y
0   1     a     p
1   2     b     q
2   9   NaN     r
3   8   NaN     s
4   5     e     t

In [78]:
join_res=pd.merge(a,b,how='outer',on='i1')
join_res

   i1 val_x val_y
0   1     a     p
1   2     b     q
2   3     c   NaN
3   4     d   NaN
4   5     e     t
5   8   NaN     s
6   9   NaN     r

### Stacking in pandas

In [79]:
# Stacking helps to convert columns into rows

In [80]:
a1 = pd.DataFrame({
'Math':[50,45],
'Science':[45,50]
},index=['Ram','Hari'])

In [81]:
a1

      Math  Science
Ram     50       45
Hari    45       50

In [82]:
stacked = a1.stack() #COlumn name became part of the index'
stacked

Ram   Math       50
      Science    45
Hari  Math       45
      Science    50
dtype: int64

In [83]:
stacked.unstack()

      Math  Science
Ram     50       45
Hari    45       50

In [84]:
index=pd.MultiIndex.from_tuples([
    ('Ram','Maths'),
    ('Ram','Science'),
    ('Hari','Maths'),
    ('Hari','Science')
])
df3 = pd.DataFrame({
    'Marks':[50,49,50,55]
},index=index)

In [85]:
print(df3.stack())

Ram   Maths    Marks    50
      Science  Marks    49
Hari  Maths    Marks    50
      Science  Marks    55
dtype: int64

### Data Reshaping functions (pivot table() and melt())

#### PIVOT TABLE

In [86]:
df4 = pd.DataFrame({
    'Name': ['Ram', 'Ram', 'Hari', 'Hari'],
    'Subject': ['Math', 'Science', 'Math', 'Science'],
    'Marks': [90, 85, 80, 75]
})

print(df4)

   Name  Subject  Marks
0   Ram     Math     90
1   Ram  Science     85
2  Hari     Math     80
3  Hari  Science     75

In [87]:
table = df4.pivot_table(
    index='Name',
    columns='Subject',
    values='Marks'
    
)

In [88]:
table

Subject  Math  Science
Name
Hari     80.0     75.0
Ram      90.0     85.0

In [89]:
df5 = pd.DataFrame({
    'Name': ['Ram', 'Ram'],
    'Subject': ['Math', 'Math'],
    'Marks': [90, 85,]
})

print(df5)

  Name Subject  Marks
0  Ram    Math     90
1  Ram    Math     85

In [90]:
# It returns the aggregate function by default (mean)
# Returned average marks of Ram in Maths
table1=df5.pivot_table(
    index='Name',
    columns='Subject',
    values='Marks'
)
table1

Subject  Math
Name
Ram      87.5

In [91]:
# To change aggregate function we have to explicitly change it 
table1=df5.pivot_table(
    index='Name',
    columns='Subject',
    values='Marks',
    aggfunc='sum'
)
table1

Subject  Math
Name
Ram       175

#### MELT()

In [92]:
df6 = pd.DataFrame({
    'Name': ['Ram', 'Hari'],
    'Math': [90, 80],
    'Science': [85, 75]
})

pd.melt(df6,id_vars='Name')

   Name variable  value
0   Ram     Math     90
1  Hari     Math     80
2   Ram  Science     85
3  Hari  Science     75

In [93]:
pwd

'C:\\Users\\Dell\\pythonlibraries\\pandas'

In [94]:
!git add .

In [95]:
!git commit -m "Add new functions"

On branch main
Your branch is up to date with 'origin/main'.

nothing to commit, working tree clean

In [96]:
!git push origin

Everything up-to-date

In [100]:
# chunks = pd.read_csv("winedata.csv", chunksize=100)

# for chunk in chunks:
#     print(chunk.head())

In [102]:
df.duplicated()

0    False
1    False
2    False
3    False
dtype: bool

In [106]:
newdf=pd.read_csv('winedata.csv')

In [114]:
newdf1 = pd.DataFrame({
    'Name':['Alice','Bob','Alice','Charlie'],
    'Age':[25,30,25,21]
})

In [121]:
newdf1.duplicated() #this is defualt keep = 'first' top-bottom, keep first occurence

0    False
1    False
2     True
3    False
dtype: bool

In [122]:
newdf1.duplicated(keep='last') #bottom-up keep last occurence

0     True
1    False
2    False
3    False
dtype: bool

In [124]:
newdf1.duplicated(keep=False) #it will show true to all the duplicates values

0     True
1    False
2     True
3    False
dtype: bool

In [130]:
newdf1.duplicated(subset=['Name'])

0    False
1    False
3    False
dtype: bool

In [ ]:
# newdf1=newdf1.drop_duplicates()
# newdf1

### String handling in pandas

In [173]:
df=pd.DataFrame({
    'Data':['1987_M_US_1','1990?_M_UK_1','1992_F_US_2','1970?_M_IT_1','1985_F_I T_2']
})
df

           Data
0   1987_M_US_1
1  1990?_M_UK_1
2   1992_F_US_2
3  1970?_M_IT_1
4  1985_F_I T_2

In [174]:
df['Data'].str.split('_') #It splits the data where it sees _

0     [1987, M, US, 1]
1    [1990?, M, UK, 1]
2     [1992, F, US, 2]
3    [1970?, M, IT, 1]
4    [1985, F, I T, 2]
Name: Data, dtype: object

In [175]:
df = df['Data'].str.split('_',expand=True)
#splits and show the splitted elemetns on separate columnn

In [176]:
df.columns=['Year','Gender','Country','No.of children']
df

    Year Gender Country No.of children
0   1987      M      US              1
1  1990?      M      UK              1
2   1992      F      US              2
3  1970?      M      IT              1
4   1985      F     I T              2

In [177]:
df['Year'].str.contains('\?')

0    False
1     True
2    False
3     True
4    False
Name: Year, dtype: bool

In [178]:
df['Country'].str.contains('U')

0     True
1     True
2     True
3    False
4    False
Name: Country, dtype: bool

In [179]:
df['Country'].str.strip()

0     US
1     UK
2     US
3     IT
4    I T
Name: Country, dtype: object

In [180]:
df['Country'].str.replace(' ','')

0    US
1    UK
2    US
3    IT
4    IT
Name: Country, dtype: object

In [181]:
df['Country'].str.upper()

0     US
1     UK
2     US
3     IT
4    I T
Name: Country, dtype: object

In [182]:
df['Country'].str.upper()

0     US
1     UK
2     US
3     IT
4    I T
Name: Country, dtype: object

In [183]:
df['Name']=['Alex','Bob','Charlie','ZAin','ALEXa']

In [184]:
df

    Year Gender Country No.of children     Name
0   1987      M      US              1     Alex
1  1990?      M      UK              1      Bob
2   1992      F      US              2  Charlie
3  1970?      M      IT              1     ZAin
4   1985      F     I T              2    ALEXa

In [185]:
df['Name'].str.capitalize() #It wil capitalize first letter and convert others to lowercase

0       Alex
1        Bob
2    Charlie
3       Zain
4      Alexa
Name: Name, dtype: object

In [186]:
df['Name'].str.title()

0       Alex
1        Bob
2    Charlie
3       Zain
4      Alexa
Name: Name, dtype: object

In [197]:
df['Last_name']=['Chettri','Chettri','Sapkota','KC','KC']
df

    Year Gender Country No.of children     Name Last_name
0   1987      M      US              1     Alex   Chettri
1  1990?      M      UK              1      Bob   Chettri
2   1992      F      US              2  Charlie   Sapkota
3  1970?      M      IT              1     ZAin        KC
4   1985      F     I T              2    ALEXa        KC

In [213]:
df["Name"]=df["Name"].str.cat(df['Last_name'], sep =" ")
# df["Full_Name"] = df["Name"] + " " + df["Last_name"]

In [210]:
df

    Year Gender Country No.of children             Name Last_name
0   1987      M      US              1     Alex Chettri   Chettri
1  1990?      M      UK              1      Bob Chettri   Chettri
2   1992      F      US              2  Charlie Sapkota   Sapkota
3  1970?      M      IT              1          ZAin KC        KC
4   1985      F     I T              2         ALEXa KC        KC

### Working with dates

In [214]:
from datetime import date

In [218]:
d = date(2026,8,4)
print(type(d))

<class 'datetime.date'>

In [219]:
print(d.year)

2026