In [1]:
import pandas as pd

In [2]:
pd.DataFrame({'A':[1,2,3]})

   A
0  1
1  2
2  3

In [3]:
pd.Series({'A':[1,2,3]})

A    [1, 2, 3]
dtype: object

In [4]:
import numpy as np
s = pd.Series([1,3,5,np.nan,6,8])
s

0    1.0
1    3.0
2    5.0
3    NaN
4    6.0
5    8.0
dtype: float64

### Python basics

In [5]:
import numpy as np
import pandas as pd

In [6]:
dict1 = {
    "name":['Alexa','Siri','Gemini','Deep'],
    "marks":[92,34,24,17],
    "city":['kathmandu','kolkata','New Jersey','Seoul']
}

In [7]:
df = pd.DataFrame(dict1)
df

     name  marks        city
0   Alexa     92   kathmandu
1    Siri     34     kolkata
2  Gemini     24  New Jersey
3    Deep     17       Seoul

In [8]:
df.to_csv('friends.csv')

In [9]:
df.to_csv('friends.csv',index=False)  #Removes the index column

In [10]:
df.head(2) #displays 2 rows

    name  marks       city
0  Alexa     92  kathmandu
1   Siri     34    kolkata

In [11]:
df.tail(2) #displays last 2 columns

     name  marks        city
2  Gemini     24  New Jersey
3    Deep     17       Seoul

In [12]:
df.describe()  # shows statistical analysis of given csv file

          marks
count   4.00000
mean   41.75000
std    34.21866
min    17.00000
25%    22.25000
50%    29.00000
75%    48.50000
max    92.00000

In [13]:
dict2 = {
    "Car":['Audi','BMW','porsche','ford'],
    "color":['Ashgrey','Black','Red','Whitish'],
    "Model":[12,15,11,7]
}

In [14]:
cars = pd.DataFrame(dict2)
cars

       Car    color  Model
0     Audi  Ashgrey     12
1      BMW    Black     15
2  porsche      Red     11
3     ford  Whitish      7

In [15]:
cars.to_csv('cars.csv')

In [16]:
cars

       Car    color  Model
0     Audi  Ashgrey     12
1      BMW    Black     15
2  porsche      Red     11
3     ford  Whitish      7

In [17]:
cars.index = ['first','second','third','fourth']
cars

            Car    color  Model
first      Audi  Ashgrey     12
second      BMW    Black     15
third   porsche      Red     11
fourth     ford  Whitish      7

In [18]:
# to access row we use index and to access column we use column name

# Pandas

In [19]:
""" opensource data analysis library, more powerful and faster with the help of numpy to make data analysis easy.
Pandas has 2 type of data structure
1. Series - 1D array with indexes, stores a single column ,capable of holding any type of data
2. DataFrame
"""

' opensource data analysis library, more powerful and faster with the help of numpy to make data analysis easy.\nPandas has 2 type of data structure\n1. Series - 1D array with indexes, stores a single column ,capable of holding any type of data\n2. DataFrame\n'

### Creating a dataframe

In [20]:
ser = pd.Series(np.random.rand(10))
type(ser)

pandas.core.series.Series

In [21]:
df1 = pd.DataFrame(np.random.rand(33,5), index=np.arange(33))

In [22]:
df1
# print(type(df1))

           0         1         2         3         4
0   0.221622  0.299204  0.963656  0.917098  0.875431
1   0.068342  0.064846  0.473393  0.579831  0.393149
2   0.871443  0.359458  0.662536  0.907522  0.933524
3   0.030582  0.477101  0.791584  0.139302  0.805935
4   0.797307  0.430569  0.490431  0.914322  0.915522
5   0.114291  0.438096  0.232124  0.710062  0.704374
6   0.474144  0.541159  0.041461  0.685823  0.198346
7   0.381430  0.493129  0.070132  0.941025  0.508095
8   0.248418  0.847150  0.065050  0.250699  0.830586
9   0.966587  0.138904  0.678789  0.174040  0.400110
10  0.025420  0.549457  0.613531  0.094196  0.193128
11  0.531259  0.424762  0.007257  0.403176  0.241045
12  0.363762  0.889494  0.525567  0.867098  0.749749
13  0.628289  0.279503  0.189833  0.575116  0.082879
14  0.565211  0.825593  0.833296  0.279183  0.090206
15  0.910575  0.462281  0.882907  0.672280  0.354252
16  0.960842  0.987443  0.254767  0.557692  0.429965
17  0.122724  0.382256  0.564242  0.121196  0.850061
18  0.851319  0.751833  0.068575  0.212640  0.930007
19  0.373293  0.869894  0.017218  0.639075  0.572439
20  0.110702  0.446627  0.238600  0.275031  0.470423
21  0.642889  0.683262  0.694511  0.129298  0.004017
22  0.578836  0.871547  0.928532  0.615990  0.234938
23  0.939602  0.161774  0.717246  0.795203  0.881003
24  0.030244  0.262330  0.011200  0.746107  0.500194
25  0.181979  0.175439  0.791106  0.348502  0.104418
26  0.563959  0.198392  0.792198  0.942145  0.004551
27  0.974689  0.471412  0.788836  0.406393  0.878358
28  0.356891  0.911972  0.886392  0.157292  0.020660
29  0.618366  0.222211  0.339464  0.185816  0.246038
30  0.053041  0.985652  0.144493  0.387430  0.872406
31  0.429431  0.224758  0.267255  0.796565  0.970509
32  0.318243  0.266902  0.262018  0.459353  0.959239

In [23]:
df1.describe()

               0          1          2          3          4
count  33.000000  33.000000  33.000000  33.000000  33.000000
mean    0.463810   0.496800   0.463279   0.511712   0.521380
std     0.317952   0.275784   0.321429   0.286230   0.336367
min     0.025420   0.064846   0.007257   0.094196   0.004017
25%     0.181979   0.266902   0.189833   0.250699   0.234938
50%     0.429431   0.446627   0.490431   0.557692   0.500194
75%     0.642889   0.751833   0.788836   0.746107   0.872406
max     0.974689   0.987443   0.963656   0.942145   0.970509

In [24]:
df1.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [25]:
df1.head()

          0         1         2         3         4
0  0.221622  0.299204  0.963656  0.917098  0.875431
1  0.068342  0.064846  0.473393  0.579831  0.393149
2  0.871443  0.359458  0.662536  0.907522  0.933524
3  0.030582  0.477101  0.791584  0.139302  0.805935
4  0.797307  0.430569  0.490431  0.914322  0.915522

In [26]:
df1[0][0] = 0.3
df1

C:\Users\Dell\AppData\Local\Temp\ipykernel_27440\658922201.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df1[0][0] = 0.3

           0         1         2         3         4
0   0.300000  0.299204  0.963656  0.917098  0.875431
1   0.068342  0.064846  0.473393  0.579831  0.393149
2   0.871443  0.359458  0.662536  0.907522  0.933524
3   0.030582  0.477101  0.791584  0.139302  0.805935
4   0.797307  0.430569  0.490431  0.914322  0.915522
5   0.114291  0.438096  0.232124  0.710062  0.704374
6   0.474144  0.541159  0.041461  0.685823  0.198346
7   0.381430  0.493129  0.070132  0.941025  0.508095
8   0.248418  0.847150  0.065050  0.250699  0.830586
9   0.966587  0.138904  0.678789  0.174040  0.400110
10  0.025420  0.549457  0.613531  0.094196  0.193128
11  0.531259  0.424762  0.007257  0.403176  0.241045
12  0.363762  0.889494  0.525567  0.867098  0.749749
13  0.628289  0.279503  0.189833  0.575116  0.082879
14  0.565211  0.825593  0.833296  0.279183  0.090206
15  0.910575  0.462281  0.882907  0.672280  0.354252
16  0.960842  0.987443  0.254767  0.557692  0.429965
17  0.122724  0.382256  0.564242  0.121196  0.850061
18  0.851319  0.751833  0.068575  0.212640  0.930007
19  0.373293  0.869894  0.017218  0.639075  0.572439
20  0.110702  0.446627  0.238600  0.275031  0.470423
21  0.642889  0.683262  0.694511  0.129298  0.004017
22  0.578836  0.871547  0.928532  0.615990  0.234938
23  0.939602  0.161774  0.717246  0.795203  0.881003
24  0.030244  0.262330  0.011200  0.746107  0.500194
25  0.181979  0.175439  0.791106  0.348502  0.104418
26  0.563959  0.198392  0.792198  0.942145  0.004551
27  0.974689  0.471412  0.788836  0.406393  0.878358
28  0.356891  0.911972  0.886392  0.157292  0.020660
29  0.618366  0.222211  0.339464  0.185816  0.246038
30  0.053041  0.985652  0.144493  0.387430  0.872406
31  0.429431  0.224758  0.267255  0.796565  0.970509
32  0.318243  0.266902  0.262018  0.459353  0.959239

In [27]:
df1.dtypes
df1.head()

          0         1         2         3         4
0  0.300000  0.299204  0.963656  0.917098  0.875431
1  0.068342  0.064846  0.473393  0.579831  0.393149
2  0.871443  0.359458  0.662536  0.907522  0.933524
3  0.030582  0.477101  0.791584  0.139302  0.805935
4  0.797307  0.430569  0.490431  0.914322  0.915522

In [28]:
df1.tail()

           0         1         2         3         4
28  0.356891  0.911972  0.886392  0.157292  0.020660
29  0.618366  0.222211  0.339464  0.185816  0.246038
30  0.053041  0.985652  0.144493  0.387430  0.872406
31  0.429431  0.224758  0.267255  0.796565  0.970509
32  0.318243  0.266902  0.262018  0.459353  0.959239

In [29]:
df1.index

Index([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32],
      dtype='int64')

In [30]:
df1.columns

RangeIndex(start=0, stop=5, step=1)

In [31]:
df1.to_numpy()

array([[0.3       , 0.29920374, 0.96365566, 0.91709803, 0.87543058],
       [0.06834186, 0.06484607, 0.47339278, 0.57983083, 0.39314926],
       [0.87144301, 0.35945848, 0.66253611, 0.90752152, 0.93352449],
       [0.03058154, 0.47710118, 0.79158434, 0.13930171, 0.80593527],
       [0.79730653, 0.43056911, 0.4904311 , 0.91432165, 0.91552203],
       [0.11429117, 0.43809608, 0.23212392, 0.71006213, 0.70437424],
       [0.47414386, 0.54115877, 0.04146059, 0.68582286, 0.19834558],
       [0.38143034, 0.49312886, 0.07013236, 0.94102514, 0.50809493],
       [0.24841794, 0.84714961, 0.0650497 , 0.25069904, 0.83058587],
       [0.966587  , 0.13890371, 0.67878921, 0.17403997, 0.40011041],
       [0.02541988, 0.54945676, 0.61353079, 0.09419603, 0.19312823],
       [0.53125945, 0.42476241, 0.0072566 , 0.40317612, 0.24104467],
       [0.3637616 , 0.88949446, 0.52556654, 0.86709789, 0.74974895],
       [0.62828857, 0.27950324, 0.18983278, 0.57511611, 0.08287899],
       [0.56521145, 0.82559333, 0.83329634, 0.2791832 , 0.09020595],
       [0.91057547, 0.46228132, 0.88290659, 0.67228006, 0.35425153],
       [0.96084209, 0.98744273, 0.25476739, 0.55769164, 0.42996478],
       [0.12272356, 0.38225618, 0.56424177, 0.12119609, 0.85006134],
       [0.85131946, 0.75183336, 0.06857461, 0.21263987, 0.93000699],
       [0.37329261, 0.86989441, 0.01721773, 0.63907548, 0.57243945],
       [0.11070178, 0.44662701, 0.23860018, 0.27503092, 0.4704225 ],
       [0.64288877, 0.68326229, 0.69451075, 0.12929784, 0.0040168 ],
       [0.57883642, 0.87154677, 0.92853232, 0.61599028, 0.23493812],
       [0.93960224, 0.16177383, 0.71724595, 0.79520302, 0.8810025 ],
       [0.03024443, 0.26232983, 0.01119963, 0.74610737, 0.50019375],
       [0.18197861, 0.17543905, 0.79110612, 0.34850213, 0.10441848],
       [0.56395882, 0.19839152, 0.79219753, 0.94214501, 0.00455068],
       [0.97468908, 0.47141186, 0.78883642, 0.4063931 , 0.87835792],
       [0.3568914 , 0.91197162, 0.88639244, 0.157292  , 0.02065988],
       [0.61836626, 0.22221136, 0.33946413, 0.18581573, 0.24603781],
       [0.05304059, 0.98565183, 0.14449261, 0.38743049, 0.87240601],
       [0.42943052, 0.22475759, 0.2672547 , 0.79656497, 0.97050929],
       [0.31824274, 0.2669024 , 0.26201818, 0.45935313, 0.95923875]])

In [32]:
df1.dtypes

0    float64
1    float64
2    float64
3    float64
4    float64
dtype: object

In [33]:
df1.T # To create transpose of df1

,0,1,2,3,4,5,6,7,8,9,...,23,24,25,26,27,28,29,30,31,32
0,0.300000,0.068342,0.871443,0.030582,0.797307,0.114291,0.474144,0.381430,0.248418,0.966587,...,0.939602,0.030244,0.181979,0.563959,0.974689,0.356891,0.618366,0.053041,0.429431,0.318243
1,0.299204,0.064846,0.359458,0.477101,0.430569,0.438096,0.541159,0.493129,0.847150,0.138904,...,0.161774,0.262330,0.175439,0.198392,0.471412,0.911972,0.222211,0.985652,0.224758,0.266902
2,0.963656,0.473393,0.662536,0.791584,0.490431,0.232124,0.041461,0.070132,0.065050,0.678789,...,0.717246,0.011200,0.791106,0.792198,0.788836,0.886392,0.339464,0.144493,0.267255,0.262018
3,0.917098,0.579831,0.907522,0.139302,0.914322,0.710062,0.685823,0.941025,0.250699,0.174040,...,0.795203,0.746107,0.348502,0.942145,0.406393,0.157292,0.185816,0.387430,0.796565,0.459353
4,0.875431,0.393149,0.933524,0.805935,0.915522,0.704374,0.198346,0.508095,0.830586,0.400110,...,0.881003,0.500194,0.104418,0.004551,0.878358,0.020660,0.246038,0.872406,0.970509,0.959239

In [34]:
df1.sort_index(axis=0,ascending=False)

           0         1         2         3         4
32  0.318243  0.266902  0.262018  0.459353  0.959239
31  0.429431  0.224758  0.267255  0.796565  0.970509
30  0.053041  0.985652  0.144493  0.387430  0.872406
29  0.618366  0.222211  0.339464  0.185816  0.246038
28  0.356891  0.911972  0.886392  0.157292  0.020660
27  0.974689  0.471412  0.788836  0.406393  0.878358
26  0.563959  0.198392  0.792198  0.942145  0.004551
25  0.181979  0.175439  0.791106  0.348502  0.104418
24  0.030244  0.262330  0.011200  0.746107  0.500194
23  0.939602  0.161774  0.717246  0.795203  0.881003
22  0.578836  0.871547  0.928532  0.615990  0.234938
21  0.642889  0.683262  0.694511  0.129298  0.004017
20  0.110702  0.446627  0.238600  0.275031  0.470423
19  0.373293  0.869894  0.017218  0.639075  0.572439
18  0.851319  0.751833  0.068575  0.212640  0.930007
17  0.122724  0.382256  0.564242  0.121196  0.850061
16  0.960842  0.987443  0.254767  0.557692  0.429965
15  0.910575  0.462281  0.882907  0.672280  0.354252
14  0.565211  0.825593  0.833296  0.279183  0.090206
13  0.628289  0.279503  0.189833  0.575116  0.082879
12  0.363762  0.889494  0.525567  0.867098  0.749749
11  0.531259  0.424762  0.007257  0.403176  0.241045
10  0.025420  0.549457  0.613531  0.094196  0.193128
9   0.966587  0.138904  0.678789  0.174040  0.400110
8   0.248418  0.847150  0.065050  0.250699  0.830586
7   0.381430  0.493129  0.070132  0.941025  0.508095
6   0.474144  0.541159  0.041461  0.685823  0.198346
5   0.114291  0.438096  0.232124  0.710062  0.704374
4   0.797307  0.430569  0.490431  0.914322  0.915522
3   0.030582  0.477101  0.791584  0.139302  0.805935
2   0.871443  0.359458  0.662536  0.907522  0.933524
1   0.068342  0.064846  0.473393  0.579831  0.393149
0   0.300000  0.299204  0.963656  0.917098  0.875431

In [35]:
df1.sort_index(axis=1,ascending = False)

           4         3         2         1         0
0   0.875431  0.917098  0.963656  0.299204  0.300000
1   0.393149  0.579831  0.473393  0.064846  0.068342
2   0.933524  0.907522  0.662536  0.359458  0.871443
3   0.805935  0.139302  0.791584  0.477101  0.030582
4   0.915522  0.914322  0.490431  0.430569  0.797307
5   0.704374  0.710062  0.232124  0.438096  0.114291
6   0.198346  0.685823  0.041461  0.541159  0.474144
7   0.508095  0.941025  0.070132  0.493129  0.381430
8   0.830586  0.250699  0.065050  0.847150  0.248418
9   0.400110  0.174040  0.678789  0.138904  0.966587
10  0.193128  0.094196  0.613531  0.549457  0.025420
11  0.241045  0.403176  0.007257  0.424762  0.531259
12  0.749749  0.867098  0.525567  0.889494  0.363762
13  0.082879  0.575116  0.189833  0.279503  0.628289
14  0.090206  0.279183  0.833296  0.825593  0.565211
15  0.354252  0.672280  0.882907  0.462281  0.910575
16  0.429965  0.557692  0.254767  0.987443  0.960842
17  0.850061  0.121196  0.564242  0.382256  0.122724
18  0.930007  0.212640  0.068575  0.751833  0.851319
19  0.572439  0.639075  0.017218  0.869894  0.373293
20  0.470423  0.275031  0.238600  0.446627  0.110702
21  0.004017  0.129298  0.694511  0.683262  0.642889
22  0.234938  0.615990  0.928532  0.871547  0.578836
23  0.881003  0.795203  0.717246  0.161774  0.939602
24  0.500194  0.746107  0.011200  0.262330  0.030244
25  0.104418  0.348502  0.791106  0.175439  0.181979
26  0.004551  0.942145  0.792198  0.198392  0.563959
27  0.878358  0.406393  0.788836  0.471412  0.974689
28  0.020660  0.157292  0.886392  0.911972  0.356891
29  0.246038  0.185816  0.339464  0.222211  0.618366
30  0.872406  0.387430  0.144493  0.985652  0.053041
31  0.970509  0.796565  0.267255  0.224758  0.429431
32  0.959239  0.459353  0.262018  0.266902  0.318243

In [36]:
df1[0]

0     0.300000
1     0.068342
2     0.871443
3     0.030582
4     0.797307
5     0.114291
6     0.474144
7     0.381430
8     0.248418
9     0.966587
10    0.025420
11    0.531259
12    0.363762
13    0.628289
14    0.565211
15    0.910575
16    0.960842
17    0.122724
18    0.851319
19    0.373293
20    0.110702
21    0.642889
22    0.578836
23    0.939602
24    0.030244
25    0.181979
26    0.563959
27    0.974689
28    0.356891
29    0.618366
30    0.053041
31    0.429431
32    0.318243
Name: 0, dtype: float64

In [37]:
df1[0]

0     0.300000
1     0.068342
2     0.871443
3     0.030582
4     0.797307
5     0.114291
6     0.474144
7     0.381430
8     0.248418
9     0.966587
10    0.025420
11    0.531259
12    0.363762
13    0.628289
14    0.565211
15    0.910575
16    0.960842
17    0.122724
18    0.851319
19    0.373293
20    0.110702
21    0.642889
22    0.578836
23    0.939602
24    0.030244
25    0.181979
26    0.563959
27    0.974689
28    0.356891
29    0.618366
30    0.053041
31    0.429431
32    0.318243
Name: 0, dtype: float64

### Copy and view

In [38]:
df2 = df1  # changes the change in new arrayb as well as referenced original array

In [39]:
df2[0][0]=988

In [40]:
df3 = df1.copy()

In [41]:
df3[0][1]=999

C:\Users\Dell\AppData\Local\Temp\ipykernel_27440\2672374281.py:1: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  df3[0][1]=999

In [42]:
df1

             0         1         2         3         4
0   988.000000  0.299204  0.963656  0.917098  0.875431
1     0.068342  0.064846  0.473393  0.579831  0.393149
2     0.871443  0.359458  0.662536  0.907522  0.933524
3     0.030582  0.477101  0.791584  0.139302  0.805935
4     0.797307  0.430569  0.490431  0.914322  0.915522
5     0.114291  0.438096  0.232124  0.710062  0.704374
6     0.474144  0.541159  0.041461  0.685823  0.198346
7     0.381430  0.493129  0.070132  0.941025  0.508095
8     0.248418  0.847150  0.065050  0.250699  0.830586
9     0.966587  0.138904  0.678789  0.174040  0.400110
10    0.025420  0.549457  0.613531  0.094196  0.193128
11    0.531259  0.424762  0.007257  0.403176  0.241045
12    0.363762  0.889494  0.525567  0.867098  0.749749
13    0.628289  0.279503  0.189833  0.575116  0.082879
14    0.565211  0.825593  0.833296  0.279183  0.090206
15    0.910575  0.462281  0.882907  0.672280  0.354252
16    0.960842  0.987443  0.254767  0.557692  0.429965
17    0.122724  0.382256  0.564242  0.121196  0.850061
18    0.851319  0.751833  0.068575  0.212640  0.930007
19    0.373293  0.869894  0.017218  0.639075  0.572439
20    0.110702  0.446627  0.238600  0.275031  0.470423
21    0.642889  0.683262  0.694511  0.129298  0.004017
22    0.578836  0.871547  0.928532  0.615990  0.234938
23    0.939602  0.161774  0.717246  0.795203  0.881003
24    0.030244  0.262330  0.011200  0.746107  0.500194
25    0.181979  0.175439  0.791106  0.348502  0.104418
26    0.563959  0.198392  0.792198  0.942145  0.004551
27    0.974689  0.471412  0.788836  0.406393  0.878358
28    0.356891  0.911972  0.886392  0.157292  0.020660
29    0.618366  0.222211  0.339464  0.185816  0.246038
30    0.053041  0.985652  0.144493  0.387430  0.872406
31    0.429431  0.224758  0.267255  0.796565  0.970509
32    0.318243  0.266902  0.262018  0.459353  0.959239

In [43]:
df3

             0         1         2         3         4
0   988.000000  0.299204  0.963656  0.917098  0.875431
1   999.000000  0.064846  0.473393  0.579831  0.393149
2     0.871443  0.359458  0.662536  0.907522  0.933524
3     0.030582  0.477101  0.791584  0.139302  0.805935
4     0.797307  0.430569  0.490431  0.914322  0.915522
5     0.114291  0.438096  0.232124  0.710062  0.704374
6     0.474144  0.541159  0.041461  0.685823  0.198346
7     0.381430  0.493129  0.070132  0.941025  0.508095
8     0.248418  0.847150  0.065050  0.250699  0.830586
9     0.966587  0.138904  0.678789  0.174040  0.400110
10    0.025420  0.549457  0.613531  0.094196  0.193128
11    0.531259  0.424762  0.007257  0.403176  0.241045
12    0.363762  0.889494  0.525567  0.867098  0.749749
13    0.628289  0.279503  0.189833  0.575116  0.082879
14    0.565211  0.825593  0.833296  0.279183  0.090206
15    0.910575  0.462281  0.882907  0.672280  0.354252
16    0.960842  0.987443  0.254767  0.557692  0.429965
17    0.122724  0.382256  0.564242  0.121196  0.850061
18    0.851319  0.751833  0.068575  0.212640  0.930007
19    0.373293  0.869894  0.017218  0.639075  0.572439
20    0.110702  0.446627  0.238600  0.275031  0.470423
21    0.642889  0.683262  0.694511  0.129298  0.004017
22    0.578836  0.871547  0.928532  0.615990  0.234938
23    0.939602  0.161774  0.717246  0.795203  0.881003
24    0.030244  0.262330  0.011200  0.746107  0.500194
25    0.181979  0.175439  0.791106  0.348502  0.104418
26    0.563959  0.198392  0.792198  0.942145  0.004551
27    0.974689  0.471412  0.788836  0.406393  0.878358
28    0.356891  0.911972  0.886392  0.157292  0.020660
29    0.618366  0.222211  0.339464  0.185816  0.246038
30    0.053041  0.985652  0.144493  0.387430  0.872406
31    0.429431  0.224758  0.267255  0.796565  0.970509
32    0.318243  0.266902  0.262018  0.459353  0.959239

In [44]:
df1.loc[1,1]=666

In [45]:
df1.head()

            0           1         2         3         4
0  988.000000    0.299204  0.963656  0.917098  0.875431
1    0.068342  666.000000  0.473393  0.579831  0.393149
2    0.871443    0.359458  0.662536  0.907522  0.933524
3    0.030582    0.477101  0.791584  0.139302  0.805935
4    0.797307    0.430569  0.490431  0.914322  0.915522

In [46]:
df1.columns=list("ABCDE")

In [47]:
df1.head()

            A           B         C         D         E
0  988.000000    0.299204  0.963656  0.917098  0.875431
1    0.068342  666.000000  0.473393  0.579831  0.393149
2    0.871443    0.359458  0.662536  0.907522  0.933524
3    0.030582    0.477101  0.791584  0.139302  0.805935
4    0.797307    0.430569  0.490431  0.914322  0.915522

In [48]:
df1.loc[0,'A']=99

In [49]:
df1.head()

           A           B         C         D         E
0  99.000000    0.299204  0.963656  0.917098  0.875431
1   0.068342  666.000000  0.473393  0.579831  0.393149
2   0.871443    0.359458  0.662536  0.907522  0.933524
3   0.030582    0.477101  0.791584  0.139302  0.805935
4   0.797307    0.430569  0.490431  0.914322  0.915522

In [50]:
df1.loc[0,0]=11

In [51]:
df1.head()

           A           B         C         D         E     0
0  99.000000    0.299204  0.963656  0.917098  0.875431  11.0
1   0.068342  666.000000  0.473393  0.579831  0.393149   NaN
2   0.871443    0.359458  0.662536  0.907522  0.933524   NaN
3   0.030582    0.477101  0.791584  0.139302  0.805935   NaN
4   0.797307    0.430569  0.490431  0.914322  0.915522   NaN

In [52]:
df1.drop(0,axis=1) #removes column 0

            A           B         C         D         E
0   99.000000    0.299204  0.963656  0.917098  0.875431
1    0.068342  666.000000  0.473393  0.579831  0.393149
2    0.871443    0.359458  0.662536  0.907522  0.933524
3    0.030582    0.477101  0.791584  0.139302  0.805935
4    0.797307    0.430569  0.490431  0.914322  0.915522
5    0.114291    0.438096  0.232124  0.710062  0.704374
6    0.474144    0.541159  0.041461  0.685823  0.198346
7    0.381430    0.493129  0.070132  0.941025  0.508095
8    0.248418    0.847150  0.065050  0.250699  0.830586
9    0.966587    0.138904  0.678789  0.174040  0.400110
10   0.025420    0.549457  0.613531  0.094196  0.193128
11   0.531259    0.424762  0.007257  0.403176  0.241045
12   0.363762    0.889494  0.525567  0.867098  0.749749
13   0.628289    0.279503  0.189833  0.575116  0.082879
14   0.565211    0.825593  0.833296  0.279183  0.090206
15   0.910575    0.462281  0.882907  0.672280  0.354252
16   0.960842    0.987443  0.254767  0.557692  0.429965
17   0.122724    0.382256  0.564242  0.121196  0.850061
18   0.851319    0.751833  0.068575  0.212640  0.930007
19   0.373293    0.869894  0.017218  0.639075  0.572439
20   0.110702    0.446627  0.238600  0.275031  0.470423
21   0.642889    0.683262  0.694511  0.129298  0.004017
22   0.578836    0.871547  0.928532  0.615990  0.234938
23   0.939602    0.161774  0.717246  0.795203  0.881003
24   0.030244    0.262330  0.011200  0.746107  0.500194
25   0.181979    0.175439  0.791106  0.348502  0.104418
26   0.563959    0.198392  0.792198  0.942145  0.004551
27   0.974689    0.471412  0.788836  0.406393  0.878358
28   0.356891    0.911972  0.886392  0.157292  0.020660
29   0.618366    0.222211  0.339464  0.185816  0.246038
30   0.053041    0.985652  0.144493  0.387430  0.872406
31   0.429431    0.224758  0.267255  0.796565  0.970509
32   0.318243    0.266902  0.262018  0.459353  0.959239

In [53]:
df1.loc[[1,2],['C','D']]  
#[1,2]-->access row 1,2
#['C','D']--> access column C & D

          C         D
1  0.473393  0.579831
2  0.662536  0.907522

In [54]:
df1.loc[[0,1,2,3],:]  # rows 0,1,2,3 and all columns are accessed/displayed

           A           B         C         D         E     0
0  99.000000    0.299204  0.963656  0.917098  0.875431  11.0
1   0.068342  666.000000  0.473393  0.579831  0.393149   NaN
2   0.871443    0.359458  0.662536  0.907522  0.933524   NaN
3   0.030582    0.477101  0.791584  0.139302  0.805935   NaN

In [55]:
df1.drop(0,axis=1)

            A           B         C         D         E
0   99.000000    0.299204  0.963656  0.917098  0.875431
1    0.068342  666.000000  0.473393  0.579831  0.393149
2    0.871443    0.359458  0.662536  0.907522  0.933524
3    0.030582    0.477101  0.791584  0.139302  0.805935
4    0.797307    0.430569  0.490431  0.914322  0.915522
5    0.114291    0.438096  0.232124  0.710062  0.704374
6    0.474144    0.541159  0.041461  0.685823  0.198346
7    0.381430    0.493129  0.070132  0.941025  0.508095
8    0.248418    0.847150  0.065050  0.250699  0.830586
9    0.966587    0.138904  0.678789  0.174040  0.400110
10   0.025420    0.549457  0.613531  0.094196  0.193128
11   0.531259    0.424762  0.007257  0.403176  0.241045
12   0.363762    0.889494  0.525567  0.867098  0.749749
13   0.628289    0.279503  0.189833  0.575116  0.082879
14   0.565211    0.825593  0.833296  0.279183  0.090206
15   0.910575    0.462281  0.882907  0.672280  0.354252
16   0.960842    0.987443  0.254767  0.557692  0.429965
17   0.122724    0.382256  0.564242  0.121196  0.850061
18   0.851319    0.751833  0.068575  0.212640  0.930007
19   0.373293    0.869894  0.017218  0.639075  0.572439
20   0.110702    0.446627  0.238600  0.275031  0.470423
21   0.642889    0.683262  0.694511  0.129298  0.004017
22   0.578836    0.871547  0.928532  0.615990  0.234938
23   0.939602    0.161774  0.717246  0.795203  0.881003
24   0.030244    0.262330  0.011200  0.746107  0.500194
25   0.181979    0.175439  0.791106  0.348502  0.104418
26   0.563959    0.198392  0.792198  0.942145  0.004551
27   0.974689    0.471412  0.788836  0.406393  0.878358
28   0.356891    0.911972  0.886392  0.157292  0.020660
29   0.618366    0.222211  0.339464  0.185816  0.246038
30   0.053041    0.985652  0.144493  0.387430  0.872406
31   0.429431    0.224758  0.267255  0.796565  0.970509
32   0.318243    0.266902  0.262018  0.459353  0.959239

In [56]:
df1.loc[(df1['A']<0.9) & (df1['C']>0.9)]

           A         B         C        D         E   0
22  0.578836  0.871547  0.928532  0.61599  0.234938 NaN

In [57]:
df1.head(2)

           A           B         C         D         E     0
0  99.000000    0.299204  0.963656  0.917098  0.875431  11.0
1   0.068342  666.000000  0.473393  0.579831  0.393149   NaN

In [58]:
df1.iloc[0,4]  # references A,B,C as index 0,1,2 so return value of (0,E)

np.float64(0.8754305842574341)

In [59]:
df1.iloc[[0,1],[1,2]]

            B         C
0    0.299204  0.963656
1  666.000000  0.473393

In [60]:
df1.head(3)

           A           B         C         D         E     0
0  99.000000    0.299204  0.963656  0.917098  0.875431  11.0
1   0.068342  666.000000  0.473393  0.579831  0.393149   NaN
2   0.871443    0.359458  0.662536  0.907522  0.933524   NaN

In [61]:
df1.drop(1)  #It doesnot remove from oe=riginal array only drops in copy

            A         B         C         D         E     0
0   99.000000  0.299204  0.963656  0.917098  0.875431  11.0
2    0.871443  0.359458  0.662536  0.907522  0.933524   NaN
3    0.030582  0.477101  0.791584  0.139302  0.805935   NaN
4    0.797307  0.430569  0.490431  0.914322  0.915522   NaN
5    0.114291  0.438096  0.232124  0.710062  0.704374   NaN
6    0.474144  0.541159  0.041461  0.685823  0.198346   NaN
7    0.381430  0.493129  0.070132  0.941025  0.508095   NaN
8    0.248418  0.847150  0.065050  0.250699  0.830586   NaN
9    0.966587  0.138904  0.678789  0.174040  0.400110   NaN
10   0.025420  0.549457  0.613531  0.094196  0.193128   NaN
11   0.531259  0.424762  0.007257  0.403176  0.241045   NaN
12   0.363762  0.889494  0.525567  0.867098  0.749749   NaN
13   0.628289  0.279503  0.189833  0.575116  0.082879   NaN
14   0.565211  0.825593  0.833296  0.279183  0.090206   NaN
15   0.910575  0.462281  0.882907  0.672280  0.354252   NaN
16   0.960842  0.987443  0.254767  0.557692  0.429965   NaN
17   0.122724  0.382256  0.564242  0.121196  0.850061   NaN
18   0.851319  0.751833  0.068575  0.212640  0.930007   NaN
19   0.373293  0.869894  0.017218  0.639075  0.572439   NaN
20   0.110702  0.446627  0.238600  0.275031  0.470423   NaN
21   0.642889  0.683262  0.694511  0.129298  0.004017   NaN
22   0.578836  0.871547  0.928532  0.615990  0.234938   NaN
23   0.939602  0.161774  0.717246  0.795203  0.881003   NaN
24   0.030244  0.262330  0.011200  0.746107  0.500194   NaN
25   0.181979  0.175439  0.791106  0.348502  0.104418   NaN
26   0.563959  0.198392  0.792198  0.942145  0.004551   NaN
27   0.974689  0.471412  0.788836  0.406393  0.878358   NaN
28   0.356891  0.911972  0.886392  0.157292  0.020660   NaN
29   0.618366  0.222211  0.339464  0.185816  0.246038   NaN
30   0.053041  0.985652  0.144493  0.387430  0.872406   NaN
31   0.429431  0.224758  0.267255  0.796565  0.970509   NaN
32   0.318243  0.266902  0.262018  0.459353  0.959239   NaN

In [62]:
df1.drop(['A','B'],axis=1,inplace=True)

In [63]:
df1

           C         D         E     0
0   0.963656  0.917098  0.875431  11.0
1   0.473393  0.579831  0.393149   NaN
2   0.662536  0.907522  0.933524   NaN
3   0.791584  0.139302  0.805935   NaN
4   0.490431  0.914322  0.915522   NaN
5   0.232124  0.710062  0.704374   NaN
6   0.041461  0.685823  0.198346   NaN
7   0.070132  0.941025  0.508095   NaN
8   0.065050  0.250699  0.830586   NaN
9   0.678789  0.174040  0.400110   NaN
10  0.613531  0.094196  0.193128   NaN
11  0.007257  0.403176  0.241045   NaN
12  0.525567  0.867098  0.749749   NaN
13  0.189833  0.575116  0.082879   NaN
14  0.833296  0.279183  0.090206   NaN
15  0.882907  0.672280  0.354252   NaN
16  0.254767  0.557692  0.429965   NaN
17  0.564242  0.121196  0.850061   NaN
18  0.068575  0.212640  0.930007   NaN
19  0.017218  0.639075  0.572439   NaN
20  0.238600  0.275031  0.470423   NaN
21  0.694511  0.129298  0.004017   NaN
22  0.928532  0.615990  0.234938   NaN
23  0.717246  0.795203  0.881003   NaN
24  0.011200  0.746107  0.500194   NaN
25  0.791106  0.348502  0.104418   NaN
26  0.792198  0.942145  0.004551   NaN
27  0.788836  0.406393  0.878358   NaN
28  0.886392  0.157292  0.020660   NaN
29  0.339464  0.185816  0.246038   NaN
30  0.144493  0.387430  0.872406   NaN
31  0.267255  0.796565  0.970509   NaN
32  0.262018  0.459353  0.959239   NaN

In [64]:
df1.drop([3,4],axis=0,inplace=True)

In [65]:
df1

           C         D         E     0
0   0.963656  0.917098  0.875431  11.0
1   0.473393  0.579831  0.393149   NaN
2   0.662536  0.907522  0.933524   NaN
5   0.232124  0.710062  0.704374   NaN
6   0.041461  0.685823  0.198346   NaN
7   0.070132  0.941025  0.508095   NaN
8   0.065050  0.250699  0.830586   NaN
9   0.678789  0.174040  0.400110   NaN
10  0.613531  0.094196  0.193128   NaN
11  0.007257  0.403176  0.241045   NaN
12  0.525567  0.867098  0.749749   NaN
13  0.189833  0.575116  0.082879   NaN
14  0.833296  0.279183  0.090206   NaN
15  0.882907  0.672280  0.354252   NaN
16  0.254767  0.557692  0.429965   NaN
17  0.564242  0.121196  0.850061   NaN
18  0.068575  0.212640  0.930007   NaN
19  0.017218  0.639075  0.572439   NaN
20  0.238600  0.275031  0.470423   NaN
21  0.694511  0.129298  0.004017   NaN
22  0.928532  0.615990  0.234938   NaN
23  0.717246  0.795203  0.881003   NaN
24  0.011200  0.746107  0.500194   NaN
25  0.791106  0.348502  0.104418   NaN
26  0.792198  0.942145  0.004551   NaN
27  0.788836  0.406393  0.878358   NaN
28  0.886392  0.157292  0.020660   NaN
29  0.339464  0.185816  0.246038   NaN
30  0.144493  0.387430  0.872406   NaN
31  0.267255  0.796565  0.970509   NaN
32  0.262018  0.459353  0.959239   NaN

In [66]:
df1.reset_index(drop=True,inplace=True)

In [67]:
df1

           C         D         E     0
0   0.963656  0.917098  0.875431  11.0
1   0.473393  0.579831  0.393149   NaN
2   0.662536  0.907522  0.933524   NaN
3   0.232124  0.710062  0.704374   NaN
4   0.041461  0.685823  0.198346   NaN
5   0.070132  0.941025  0.508095   NaN
6   0.065050  0.250699  0.830586   NaN
7   0.678789  0.174040  0.400110   NaN
8   0.613531  0.094196  0.193128   NaN
9   0.007257  0.403176  0.241045   NaN
10  0.525567  0.867098  0.749749   NaN
11  0.189833  0.575116  0.082879   NaN
12  0.833296  0.279183  0.090206   NaN
13  0.882907  0.672280  0.354252   NaN
14  0.254767  0.557692  0.429965   NaN
15  0.564242  0.121196  0.850061   NaN
16  0.068575  0.212640  0.930007   NaN
17  0.017218  0.639075  0.572439   NaN
18  0.238600  0.275031  0.470423   NaN
19  0.694511  0.129298  0.004017   NaN
20  0.928532  0.615990  0.234938   NaN
21  0.717246  0.795203  0.881003   NaN
22  0.011200  0.746107  0.500194   NaN
23  0.791106  0.348502  0.104418   NaN
24  0.792198  0.942145  0.004551   NaN
25  0.788836  0.406393  0.878358   NaN
26  0.886392  0.157292  0.020660   NaN
27  0.339464  0.185816  0.246038   NaN
28  0.144493  0.387430  0.872406   NaN
29  0.267255  0.796565  0.970509   NaN
30  0.262018  0.459353  0.959239   NaN

In [68]:
df1.dropna(axis=1,inplace=True)
df1

           C         D         E
0   0.963656  0.917098  0.875431
1   0.473393  0.579831  0.393149
2   0.662536  0.907522  0.933524
3   0.232124  0.710062  0.704374
4   0.041461  0.685823  0.198346
5   0.070132  0.941025  0.508095
6   0.065050  0.250699  0.830586
7   0.678789  0.174040  0.400110
8   0.613531  0.094196  0.193128
9   0.007257  0.403176  0.241045
10  0.525567  0.867098  0.749749
11  0.189833  0.575116  0.082879
12  0.833296  0.279183  0.090206
13  0.882907  0.672280  0.354252
14  0.254767  0.557692  0.429965
15  0.564242  0.121196  0.850061
16  0.068575  0.212640  0.930007
17  0.017218  0.639075  0.572439
18  0.238600  0.275031  0.470423
19  0.694511  0.129298  0.004017
20  0.928532  0.615990  0.234938
21  0.717246  0.795203  0.881003
22  0.011200  0.746107  0.500194
23  0.791106  0.348502  0.104418
24  0.792198  0.942145  0.004551
25  0.788836  0.406393  0.878358
26  0.886392  0.157292  0.020660
27  0.339464  0.185816  0.246038
28  0.144493  0.387430  0.872406
29  0.267255  0.796565  0.970509
30  0.262018  0.459353  0.959239

In [69]:
df1.drop_duplicates()

           C         D         E
0   0.963656  0.917098  0.875431
1   0.473393  0.579831  0.393149
2   0.662536  0.907522  0.933524
3   0.232124  0.710062  0.704374
4   0.041461  0.685823  0.198346
5   0.070132  0.941025  0.508095
6   0.065050  0.250699  0.830586
7   0.678789  0.174040  0.400110
8   0.613531  0.094196  0.193128
9   0.007257  0.403176  0.241045
10  0.525567  0.867098  0.749749
11  0.189833  0.575116  0.082879
12  0.833296  0.279183  0.090206
13  0.882907  0.672280  0.354252
14  0.254767  0.557692  0.429965
15  0.564242  0.121196  0.850061
16  0.068575  0.212640  0.930007
17  0.017218  0.639075  0.572439
18  0.238600  0.275031  0.470423
19  0.694511  0.129298  0.004017
20  0.928532  0.615990  0.234938
21  0.717246  0.795203  0.881003
22  0.011200  0.746107  0.500194
23  0.791106  0.348502  0.104418
24  0.792198  0.942145  0.004551
25  0.788836  0.406393  0.878358
26  0.886392  0.157292  0.020660
27  0.339464  0.185816  0.246038
28  0.144493  0.387430  0.872406
29  0.267255  0.796565  0.970509
30  0.262018  0.459353  0.959239

In [70]:
df1['C'].isnull()

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
25    False
26    False
27    False
28    False
29    False
30    False
Name: C, dtype: bool

In [71]:
df1.loc['C']=None

In [72]:
df1

           C         D         E
0   0.963656  0.917098  0.875431
1   0.473393  0.579831  0.393149
2   0.662536  0.907522  0.933524
3   0.232124  0.710062  0.704374
4   0.041461  0.685823  0.198346
5   0.070132  0.941025  0.508095
6   0.065050  0.250699  0.830586
7   0.678789  0.174040  0.400110
8   0.613531  0.094196  0.193128
9   0.007257  0.403176  0.241045
10  0.525567  0.867098  0.749749
11  0.189833  0.575116  0.082879
12  0.833296  0.279183  0.090206
13  0.882907  0.672280  0.354252
14  0.254767  0.557692  0.429965
15  0.564242  0.121196  0.850061
16  0.068575  0.212640  0.930007
17  0.017218  0.639075  0.572439
18  0.238600  0.275031  0.470423
19  0.694511  0.129298  0.004017
20  0.928532  0.615990  0.234938
21  0.717246  0.795203  0.881003
22  0.011200  0.746107  0.500194
23  0.791106  0.348502  0.104418
24  0.792198  0.942145  0.004551
25  0.788836  0.406393  0.878358
26  0.886392  0.157292  0.020660
27  0.339464  0.185816  0.246038
28  0.144493  0.387430  0.872406
29  0.267255  0.796565  0.970509
30  0.262018  0.459353  0.959239
C        NaN       NaN       NaN

In [73]:
df1.loc[:,['C']]=34

In [74]:
df1

       C         D         E
0   34.0  0.917098  0.875431
1   34.0  0.579831  0.393149
2   34.0  0.907522  0.933524
3   34.0  0.710062  0.704374
4   34.0  0.685823  0.198346
5   34.0  0.941025  0.508095
6   34.0  0.250699  0.830586
7   34.0  0.174040  0.400110
8   34.0  0.094196  0.193128
9   34.0  0.403176  0.241045
10  34.0  0.867098  0.749749
11  34.0  0.575116  0.082879
12  34.0  0.279183  0.090206
13  34.0  0.672280  0.354252
14  34.0  0.557692  0.429965
15  34.0  0.121196  0.850061
16  34.0  0.212640  0.930007
17  34.0  0.639075  0.572439
18  34.0  0.275031  0.470423
19  34.0  0.129298  0.004017
20  34.0  0.615990  0.234938
21  34.0  0.795203  0.881003
22  34.0  0.746107  0.500194
23  34.0  0.348502  0.104418
24  34.0  0.942145  0.004551
25  34.0  0.406393  0.878358
26  34.0  0.157292  0.020660
27  34.0  0.185816  0.246038
28  34.0  0.387430  0.872406
29  34.0  0.796565  0.970509
30  34.0  0.459353  0.959239
C   34.0       NaN       NaN

In [87]:
newdf = pd.DataFrame({
    "name":['Alfred','Batman','Alfred'],
    "toy":[np.nan,np.nan,np.nan],
    "born":[pd.NaT,pd.Timestamp("1940-04-25"),pd.NaT]
})

In [84]:
newdf

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [78]:
newdf.dropna()

     name        toy       born
1  Batman  Batmobile 1940-04-25

In [85]:
newdf.dropna(how='all') #doesnot drop until all records are na

       name  toy       born
0    Alfred  NaN        NaT
1    Batman  NaN 1940-04-25
2  Catwoman  NaN        NaT

In [86]:
newdf.dropna(how='all',axis=1)

       name       born
0    Alfred        NaT
1    Batman 1940-04-25
2  Catwoman        NaT

In [89]:
newdf.drop_duplicates()

     name  toy       born
0  Alfred  NaN        NaT
1  Batman  NaN 1940-04-25

In [90]:
newdf.drop_duplicates(subset=['name'])

     name  toy       born
0  Alfred  NaN        NaT
1  Batman  NaN 1940-04-25

In [92]:
newdf.drop_duplicates(subset=['name'],keep='last')

     name  toy       born
1  Batman  NaN 1940-04-25
2  Alfred  NaN        NaT

In [94]:
newdf.drop_duplicates(subset=['name'],keep=False)

     name  toy       born
1  Batman  NaN 1940-04-25

In [95]:
newdf.shape

(3, 3)

In [97]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    3 non-null      object
 1   toy     0 non-null      float64
 2   born    1 non-null      datetime64[ns]
dtypes: datetime64[ns](1), float64(1), object(1)
memory usage: 204.0+ bytes

In [98]:
newdf['name'].value_counts(dropna=False)

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [99]:
newdf['name'].value_counts(dropna=True)

name
Alfred    2
Batman    1
Name: count, dtype: int64

In [100]:
newdf.isnull()

    name   toy   born
0  False  True   True
1  False  True  False
2  False  True   True

In [102]:
#Create a datframe which contains only integers with 3 rows and 2 columns 
# Run following datdfrwame methodsz
newdf.describe()

       toy                 born
count  0.0                    1
mean   NaN  1940-04-25 00:00:00
min    NaN  1940-04-25 00:00:00
25%    NaN  1940-04-25 00:00:00
50%    NaN  1940-04-25 00:00:00
75%    NaN  1940-04-25 00:00:00
max    NaN  1940-04-25 00:00:00
std    NaN                  NaN

In [127]:
intdf = pd.DataFrame({
    'maths':[10,20,25],
    'science':[30,20,30]
})

In [128]:
intdf

   maths  science
0     10       30
1     20       20
2     25       30

In [130]:
intdf.describe()

           maths    science
count   3.000000   3.000000
mean   18.333333  26.666667
std     7.637626   5.773503
min    10.000000  20.000000
25%    15.000000  25.000000
50%    20.000000  30.000000
75%    22.500000  30.000000
max    25.000000  30.000000

In [131]:
intdf.mean()

maths      18.333333
science    26.666667
dtype: float64

In [132]:
intdf.corr()

            maths   science
maths    1.000000 -0.188982
science -0.188982  1.000000

In [133]:
intdf.count()

maths      3
science    3
dtype: int64

In [134]:
intdf.max()

maths      25
science    30
dtype: int64

In [135]:
intdf.min()

maths      10
science    20
dtype: int64

In [1]:
!git init

Initialized empty Git repository in C:/Users/Dell/pythonds/pandas/.git/

In [2]:
!git add .

warning: in the working copy of '.ipynb_checkpoints/Untitled-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.ipynb_checkpoints/pandasbasics-checkpoint.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'Untitled.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'pandasbasics.ipynb', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'winedata.csv', LF will be replaced by CRLF the next time Git touches it

In [3]:
!git commit -m "Pandas basics"

[main (root-commit) 735c5a9] Pandas basics
 8 files changed, 147520 insertions(+)
 create mode 100644 .ipynb_checkpoints/Untitled-checkpoint.ipynb
 create mode 100644 .ipynb_checkpoints/friends-checkpoint.csv
 create mode 100644 .ipynb_checkpoints/pandasbasics-checkpoint.ipynb
 create mode 100644 Cars.csv
 create mode 100644 Untitled.ipynb
 create mode 100644 friends.csv
 create mode 100644 pandasbasics.ipynb
 create mode 100644 winedata.csv

In [4]:
!git remote add origin https://github.com/binita21/Pandas.git

In [6]:
!git push -u origin main

branch 'main' set up to track 'origin/main'.

Everything up-to-date

In [7]:
!git branch main

fatal: a branch named 'main' already exists